import Joi from "joi";

const create = (data) => {
  const poHeaderSchema = Joi.object({
    PO_NUMBER: Joi.string().allow("", null),
    CO_CODE: Joi.string().allow("", null),
    DOC_CAT: Joi.string().allow("", null),
    DOC_TYPE: Joi.string().allow("", null),
    CNTRL_IND: Joi.string().allow("", null),
    DELETE_IND: Joi.string().allow("", null),
    STATUS: Joi.string().allow("", null),
    CREATED_ON: Joi.string().allow("", null),
    CREATED_BY: Joi.string().allow("", null),
    ITEM_INTVL: Joi.number().allow("", null),
    LAST_ITEM: Joi.number().allow("", null),
    VENDOR: Joi.string().allow("", null),
    LANGUAGE: Joi.string().allow("", null),
    PMNTTRMS: Joi.string().allow("", null),
    DSCNT1_TO: Joi.number().allow("", null),
    DSCNT2_TO: Joi.number().allow("", null),
    DSCNT3_TO: Joi.number().allow("", null),
    CASH_DISC1: Joi.number().allow("", null),
    CASH_DISC2: Joi.number().allow("", null),
    PURCH_ORG: Joi.string().allow("", null),
    PUR_GROUP: Joi.string().allow("", null),
    CURRENCY: Joi.string().allow("", null),
    EXCH_RATE: Joi.number().allow("", null),
    EX_RATE_FX: Joi.string().allow("", null),
    DOC_DATE: Joi.string().allow("", null),
    VPER_START: Joi.string().allow("", null),
    VPER_END: Joi.string().allow("", null),
    APPLIC_BY: Joi.string().allow("", null),
    QUOT_DEAD: Joi.string().allow("", null),
    BINDG_PER: Joi.string().allow("", null),
    WARRANTY: Joi.string().allow("", null),
    BIDINV_NO: Joi.string().allow("", null),
    QUOTATION: Joi.string().allow("", null),
    QUOT_DATE: Joi.string().allow("", null),
    REF_1: Joi.string().allow("", null),
    SALES_PERS: Joi.string().allow("", null),
    TELEPHONE: Joi.string().allow("", null),
    SUPPL_VEND: Joi.string().allow("", null),
    CUSTOMER: Joi.string().allow("", null),
    AGREEMENT: Joi.string().allow("", null),
    REJ_REASON: Joi.string().allow("", null),
    COMPL_DLV: Joi.string().allow("", null),
    GR_MESSAGE: Joi.string().allow("", null),
    SUPPL_PLNT: Joi.string().allow("", null),
    RCVG_VEND: Joi.string().allow("", null),
    INCOTERMS1: Joi.string().allow("", null),
    INCOTERMS2: Joi.string().allow("", null),
    TARGET_VAL: Joi.number().allow("", null),
    COLL_NO: Joi.string().allow("", null),
    DOC_COND: Joi.string().allow("", null),
    PROCEDURE: Joi.string().allow("", null),
    UPDATE_GRP: Joi.string().allow("", null),
    DIFF_INV: Joi.string().allow("", null),
    EXPORT_NO: Joi.string().allow("", null),
    OUR_REF: Joi.string().allow("", null),
    LOGSYSTEM: Joi.string().allow("", null),
    SUBITEMINT: Joi.number().allow("", null),
    MAST_COND: Joi.string().allow("", null),
    REL_GROUP: Joi.string().allow("", null),
    REL_STRAT: Joi.string().allow("", null),
    REL_IND: Joi.string().allow("", null),
    REL_STATUS: Joi.string().allow("", null),
    SUBJ_TO_R: Joi.string().allow("", null),
    TAXR_CNTRY: Joi.string().allow("", null),
    SCHED_IND: Joi.string().allow("", null),
    VEND_NAME: Joi.string().allow("", null),
    CURRENCY_ISO: Joi.string().allow("", null),
    EXCH_RATE_CM: Joi.number().allow("", null),
    HOLD: Joi.string().allow("", null),
  });

  const poAddressSchema = Joi.object({
    ADDRNUMBER: Joi.string().allow("", null),
    ADDRHANDLE: Joi.string().allow("", null),
    NATION: Joi.string().allow("", null),
    DATE: Joi.string().allow("", null),
    DATE_FROM: Joi.string().allow("", null),
    DATE_TO: Joi.string().allow("", null),
    TITLE: Joi.string().allow("", null),
    NAME1: Joi.string().allow("", null),
    NAME2: Joi.string().allow("", null),
    NAME3: Joi.string().allow("", null),
    NAME4: Joi.string().allow("", null),
    NAME_TXT: Joi.string().allow("", null),
    NAME_CO: Joi.string().allow("", null),
    CITY1: Joi.string().allow("", null),
    CITY2: Joi.string().allow("", null),
    CITY_CODE: Joi.string().allow("", null),
    CITYP_CODE: Joi.string().allow("", null),
    CHCKSTATUS: Joi.string().allow("", null),
    POST_CODE1: Joi.string().allow("", null),
    POST_CODE2: Joi.string().allow("", null),
    POST_CODE3: Joi.string().allow("", null),
    PO_BOX: Joi.string().allow("", null),
    PO_BOX_NUM: Joi.string().allow("", null),
    PO_BOX_LOC: Joi.string().allow("", null),
    CITY_CODE2: Joi.string().allow("", null),
    PO_BOX_REG: Joi.string().allow("", null),
    PO_BOX_CTY: Joi.string().allow("", null),
    POSTALAREA: Joi.string().allow("", null),
    TRANSPZONE: Joi.string().allow("", null),
    STREET: Joi.string().allow("", null),
    STREETCODE: Joi.string().allow("", null),
    STREETABBR: Joi.string().allow("", null),
    HOUSE_NUM1: Joi.string().allow("", null),
    HOUSE_NUM2: Joi.string().allow("", null),
    HOUSE_NUM3: Joi.string().allow("", null),
    STR_SUPPL1: Joi.string().allow("", null),
    STR_SUPPL2: Joi.string().allow("", null),
    LOCATION: Joi.string().allow("", null),
    BUILDING: Joi.string().allow("", null),
    FLOOR: Joi.string().allow("", null),
    ROOMNUMBER: Joi.string().allow("", null),
    COUNTRY: Joi.string().allow("", null),
    LANGU: Joi.string().allow("", null),
    REGION: Joi.string().allow("", null),
    SORT1: Joi.string().allow("", null),
    SORT2: Joi.string().allow("", null),
    SORT_PHN: Joi.string().allow("", null),
    ADDRORIGIN: Joi.string().allow("", null),
    EXTENSION1: Joi.string().allow("", null),
    EXTENSION2: Joi.string().allow("", null),
    TIME_ZONE: Joi.string().allow("", null),
    TAXJURCODE: Joi.string().allow("", null),
    ADDRESS_ID: Joi.string().allow("", null),
    REMARK: Joi.string().allow("", null),
    DEFLT_COMM: Joi.string().allow("", null),
    TEL_NUMBER: Joi.string().allow("", null),
    TEL_EXTENS: Joi.string().allow("", null),
    FAX_NUMBER: Joi.string().allow("", null),
    FAX_EXTENS: Joi.string().allow("", null),
    BUILD_LONG: Joi.string().allow("", null),
  });

  const poItemSchema = Joi.array().items(
    Joi.object({
      PO_NUMBER: Joi.string().allow("", null),
      PO_ITEM: Joi.number().allow("", null),
      DELETE_IND: Joi.string().allow("", null),
      STATUS: Joi.string().allow("", null),
      CHANGED_ON: Joi.string().allow("", null),
      SHORT_TEXT: Joi.string().allow("", null),
      MATERIAL: Joi.string().allow("", null),
      PUR_MAT: Joi.string().allow("", null),
      CO_CODE: Joi.string().allow("", null),
      PLANT: Joi.string().allow("", null),
      STORE_LOC: Joi.string().allow("", null),
      TRACKINGNO: Joi.string().allow("", null),
      MAT_GRP: Joi.string().allow("", null),
      INFO_REC: Joi.string().allow("", null),
      VEND_MAT: Joi.string().allow("", null),
      TARGET_QTY: Joi.number().allow("", null),
      QUANTITY: Joi.number().allow("", null),
      UNIT: Joi.string().allow("", null),
      ORDERPR_UN: Joi.string().allow("", null),
      CONV_NUM1: Joi.number().allow("", null),
      CONV_DEN1: Joi.number().allow("", null),
      CONV_NUM2: Joi.number().allow("", null),
      CONV_DEN2: Joi.number().allow("", null),
      NET_PRICE: Joi.number().allow("", null),
      PRICE_UNIT: Joi.number().allow("", null),
      NET_VALUE: Joi.number().allow("", null),
      GROS_VALUE: Joi.number().allow("", null),
      QUOT_DEAD: Joi.string().allow("", null),
      GR_PR_TIME: Joi.number().allow("", null),
      TAX_CODE: Joi.string().allow("", null),
      SETT_GRP1: Joi.string().allow("", null),
      QUAL_INSP: Joi.string().allow("", null),
      INFO_UPD: Joi.string().allow("", null),
      PRNT_PRICE: Joi.string().allow("", null),
      EST_PRICE: Joi.string().allow("", null),
      NUM_REMIND: Joi.number().allow("", null),
      REMINDER1: Joi.number().allow("", null),
      REMINDER2: Joi.number().allow("", null),
      REMINDER3: Joi.number().allow("", null),
      OVERDELTOL: Joi.number().allow("", null),
      UNLIMITED: Joi.string().allow("", null),
      UNDER_TOL: Joi.number().allow("", null),
      VAL_TYPE: Joi.string().allow("", null),
      VAL_CAT: Joi.string().allow("", null),
      REJ_IND: Joi.string().allow("", null),
      COMMENT: Joi.string().allow("", null),
      DEL_COMPL: Joi.string().allow("", null),
      FINAL_INV: Joi.string().allow("", null),
      ITEM_CAT: Joi.string().allow("", null),
      ACCTASSCAT: Joi.string().allow("", null),
      CONSUMPT: Joi.string().allow("", null),
      DISTRIB: Joi.string().allow("", null),
      PART_INV: Joi.string().allow("", null),
      GR_IND: Joi.string().allow("", null),
      GR_NON_VAL: Joi.string().allow("", null),
      IR_IND: Joi.string().allow("", null),
      GR_BASEDIV: Joi.string().allow("", null),
      ACKN_REQD: Joi.string().allow("", null),
      ACKNOWL_NO: Joi.string().allow("", null),
      AGREEMENT: Joi.string().allow("", null),
      AGMT_ITEM: Joi.number().allow("", null),
      RECON_DATE: Joi.string().allow("", null),
      AGRCUMQTY: Joi.number().allow("", null),
      FIRM_ZONE: Joi.number().allow("", null),
      TRADE_OFF: Joi.number().allow("", null),
      BOM_EXPL: Joi.string().allow("", null),
      EXCLUSION: Joi.string().allow("", null),
      BASE_UNIT: Joi.string().allow("", null),
      SHIPPING: Joi.string().allow("", null),
      OUTL_TARGV: Joi.number().allow("", null),
      NOND_ITAX: Joi.number().allow("", null),
      RELORD_QTY: Joi.number().allow("", null),
      PRICE_DATE: Joi.string().allow("", null),
      DOC_CAT: Joi.string().allow("", null),
      EFF_VALUE: Joi.number().allow("", null),
      COMMITMENT: Joi.string().allow("", null),
      CUSTOMER: Joi.string().allow("", null),
      ADDRESS: Joi.string().allow("", null),
      COND_GROUP: Joi.string().allow("", null),
      NO_C_DISC: Joi.string().allow("", null),
      UPDATE_GRP: Joi.string().allow("", null),
      PLAN_DEL: Joi.number().allow("", null),
      NET_WEIGHT: Joi.number().allow("", null),
      WEIGHTUNIT: Joi.string().allow("", null),
      TAX_JUR_CD: Joi.string().allow("", null),
      PRINT_REL: Joi.string().allow("", null),
      SPEC_STOCK: Joi.string().allow("", null),
      SETRESERNO: Joi.number().allow("", null),
      SETTLITMNO: Joi.number().allow("", null),
      NOT_CHGBL: Joi.string().allow("", null),
      CTR_KEY_QM: Joi.string().allow("", null),
      CERT_TYPE: Joi.string().allow("", null),
      EAN_UPC: Joi.string().allow("", null),
      CONF_CTRL: Joi.string().allow("", null),
      REV_LEV: Joi.string().allow("", null),
      FUND: Joi.string().allow("", null),
      FUNDS_CTR: Joi.string().allow("", null),
      CMMT_ITEM: Joi.string().allow("", null),
      BA_PARTNER: Joi.string().allow("", null),
      PTR_ASS_BA: Joi.string().allow("", null),
      PROFIT_CTR: Joi.string().allow("", null),
      PARTNER_PC: Joi.string().allow("", null),
      PRICE_CTR: Joi.string().allow("", null),
      GROSS_WGHT: Joi.number().allow("", null),
      VOLUME: Joi.number().allow("", null),
      VOLUMEUNIT: Joi.string().allow("", null),
      INCOTERMS1: Joi.string().allow("", null),
      INCOTERMS2: Joi.string().allow("", null),
      ADVANCE: Joi.string().allow("", null),
      PRIOR_VEND: Joi.string().allow("", null),
      SUB_RANGE: Joi.string().allow("", null),
      PCKG_NO: Joi.number().allow("", null),
      STATISTIC: Joi.string().allow("", null),
      HL_ITEM: Joi.number().allow("", null),
      GR_TO_DATE: Joi.string().allow("", null),
      SUPPL_VEND: Joi.string().allow("", null),
      SC_VENDOR: Joi.string().allow("", null),
      CONF_MATL: Joi.string().allow("", null),
      MAT_CAT: Joi.string().allow("", null),
      KANBAN_IND: Joi.string().allow("", null),
      ADDRESS2: Joi.string().allow("", null),
      INT_OBJ_NO: Joi.number().allow("", null),
      ERS: Joi.string().allow("", null),
      GRSETTFROM: Joi.string().allow("", null),
      LAST_TRANS: Joi.string().allow("", null),
      TRANS_TIME: Joi.string().allow("", null),
      SER_NO: Joi.number().allow("", null),
      PROMOTION: Joi.string().allow("", null),
      ALLOC_TBL: Joi.string().allow("", null),
      AT_ITEM: Joi.number().allow("", null),
      POINTS: Joi.number().allow("", null),
      POINTS_UN: Joi.string().allow("", null),
      SEASON_TY: Joi.string().allow("", null),
      SEASON_YR: Joi.string().allow("", null),
      SETT_GRP_2: Joi.string().allow("", null),
      SETT_GRP_3: Joi.string().allow("", null),
      SETT_ITEM: Joi.string().allow("", null),
      ML_AKT: Joi.string().allow("", null),
      REMSHLIFE: Joi.number().allow("", null),
      RFQ: Joi.string().allow("", null),
      RFQ_ITEM: Joi.number().allow("", null),
      CONFIG_ORG: Joi.string().allow("", null),
      QUOTAUSAGE: Joi.string().allow("", null),
      SPSTCK_PHY: Joi.string().allow("", null),
      PREQ_NO: Joi.string().allow("", null),
      PREQ_ITEM: Joi.number().allow("", null),
      MAT_TYPE: Joi.string().allow("", null),
      SI_CAT: Joi.string().allow("", null),
      SUB_ITEMS: Joi.string().allow("", null),
      SUBTOTAL_1: Joi.number().allow("", null),
      SUBTOTAL_2: Joi.number().allow("", null),
      SUBTOTAL_3: Joi.number().allow("", null),
      SUBTOTAL_4: Joi.number().allow("", null),
      SUBTOTAL_5: Joi.number().allow("", null),
      SUBTOTAL_6: Joi.number().allow("", null),
      SUBITM_KEY: Joi.string().allow("", null),
      MAX_CMG: Joi.number().allow("", null),
      MAX_CPGO: Joi.number().allow("", null),
      RET_ITEM: Joi.string().allow("", null),
      AT_RELEV: Joi.string().allow("", null),
      ORD_REAS: Joi.string().allow("", null),
      DEL_TYP_RT: Joi.string().allow("", null),
      PRDTE_CTRL: Joi.string().allow("", null),
      MANUF_PROF: Joi.string().allow("", null),
      MANU_MAT: Joi.string().allow("", null),
      MFR_NO: Joi.string().allow("", null),
      MFR_NO_EXT: Joi.string().allow("", null),
      ITEM_CAT_EXT: Joi.string().allow("", null),
      PO_UNIT_ISO: Joi.string().allow("", null),
      ORDERPR_UN_ISO: Joi.string().allow("", null),
      BASE_UOM_ISO: Joi.string().allow("", null),
      WEIGHTUNIT_ISO: Joi.string().allow("", null),
      VOLUMEUNIT_ISO: Joi.string().allow("", null),
      POINTS_UN_ISO: Joi.string().allow("", null),
      CONF_MATL_EXTERNAL: Joi.string().allow("", null),
      CONF_MATL_GUID: Joi.string().allow("", null),
      CONF_MATL_VERSION: Joi.string().allow("", null),
      MATERIAL_EXTERNAL: Joi.string().allow("", null),
      MATERIAL_GUID: Joi.string().allow("", null),
      MATERIAL_VERSION: Joi.string().allow("", null),
      PUR_MAT_EXTERNAL: Joi.string().allow("", null),
      PUR_MAT_GUID: Joi.string().allow("", null),
      PUR_MAT_VERSION: Joi.string().allow("", null),
      GRANT_NBR: Joi.string().allow("", null),
      CMMT_ITEM_LONG: Joi.string().allow("", null),
      FUNC_AREA_LONG: Joi.string().allow("", null),
      BUDGET_PERIOD: Joi.string().allow("", null),
      MATERIAL_LONG: Joi.string().allow("", null),
      PUR_MAT_LONG: Joi.string().allow("", null),
      CONF_MATL_LONG: Joi.string().allow("", null),
      ORIGINAL_QUANTITY: Joi.number().allow("", null),
    })
  );

  const poItemServicesSchema = Joi.array().items(
    Joi.object({
      PCKG_NO: Joi.number().allow("", null),
      LINE_NO: Joi.number().allow("", null),
      EXT_LINE: Joi.number().allow("", null),
      OUTL_LEVEL: Joi.number().allow("", null),
      OUTL_NO: Joi.string().allow("", null),
      OUTL_IND: Joi.string().allow("", null),
      SUBPCKG_NO: Joi.number().allow("", null),
      DELETE_IND: Joi.string().allow("", null),
      SERVICE: Joi.string().allow("", null),
      SERV_TYPE: Joi.string().allow("", null),
      EDITION: Joi.number().allow("", null),
      SSC_ITEM: Joi.string().allow("", null),
      EXT_SERV: Joi.string().allow("", null),
      QUANTITY: Joi.number().allow("", null),
      BASE_UOM: Joi.string().allow("", null),
      UOM_ISO: Joi.string().allow("", null),
      OVF_TOL: Joi.number().allow("", null),
      OVF_UNLIM: Joi.string().allow("", null),
      PRICE_UNIT: Joi.number().allow("", null),
      GROSS_VAL: Joi.number().allow("", null),
      NET_VALUE: Joi.number().allow("", null),
      FROM_LINE: Joi.string().allow("", null),
      TO_LINE: Joi.string().allow("", null),
      SHORT_TEXT: Joi.string().allow("", null),
      DISTRIB: Joi.string().allow("", null),
      PERS_NO: Joi.number().allow("", null),
      WAGETYPE: Joi.string().allow("", null),
      PLN_PCKG: Joi.number().allow("", null),
      PLN_LINE: Joi.number().allow("", null),
      CON_PCKG: Joi.number().allow("", null),
      CON_LINE: Joi.number().allow("", null),
      TMP_PCKG: Joi.number().allow("", null),
      TMP_LINE: Joi.number().allow("", null),
      SSC_LIM: Joi.string().allow("", null),
      LIMIT_LINE: Joi.number().allow("", null),
      ACTUAL_QTY: Joi.number().allow("", null),
      ACTUAL_VAL: Joi.number().allow("", null),
      CON_VALUE: Joi.number().allow("", null),
      CON_QTY: Joi.number().allow("", null),
      TARGET_VAL: Joi.number().allow("", null),
      UNPL_VAL: Joi.number().allow("", null),
      UNPL_QTY: Joi.number().allow("", null),
      BASLINE_NO: Joi.number().allow("", null),
      BASIC_LINE: Joi.string().allow("", null),
      ALTERNAT: Joi.string().allow("", null),
      BIDDER: Joi.string().allow("", null),
      SUPP_LINE: Joi.string().allow("", null),
      OPEN_QTY: Joi.string().allow("", null),
      INFORM: Joi.string().allow("", null),
      BLANKET: Joi.string().allow("", null),
      EVENTUAL: Joi.string().allow("", null),
      TAX_CODE: Joi.string().allow("", null),
      TAXJURCODE: Joi.string().allow("", null),
      PRICE_CHG: Joi.string().allow("", null),
      MATL_GROUP: Joi.string().allow("", null),
      NOND_ITAX: Joi.number().allow("", null),
      DATE: Joi.string().allow("", null),
      BEGINTIME: Joi.string().allow("", null),
      ENDTIME: Joi.string().allow("", null),
      EXTPERS_NO: Joi.string().allow("", null),
      FORMULA: Joi.string().allow("", null),
      FORM_VAL1: Joi.number().allow("", null),
      FORM_VAL2: Joi.number().allow("", null),
      FORM_VAL3: Joi.number().allow("", null),
      FORM_VAL4: Joi.number().allow("", null),
      FORM_VAL5: Joi.number().allow("", null),
      USERF1_NUM: Joi.number().allow("", null),
      USERF2_NUM: Joi.number().allow("", null),
      USERF1_TXT: Joi.string().allow("", null),
      USERF2_TXT: Joi.string().allow("", null),
      GR_PRICE: Joi.number().allow("", null),
      HI_LINE_NO: Joi.number().allow("", null),
      EXTREFKEY: Joi.string().allow("", null),
      PER_SDATE: Joi.string().allow("", null),
      PER_EDATE: Joi.string().allow("", null),
      EXTERNAL_ITEM_ID: Joi.string().allow("", null),
      SERVICE_ITEM_KEY: Joi.number().allow("", null),
      ORIGINAL_QUANTITY: Joi.number().allow("", null),
    })
  );

  const poItemScheduleSchema = Joi.array().items(
    Joi.object({
      PO_ITEM: Joi.number().allow("", null),
      SERIAL_NO: Joi.number().allow("", null),
      DEL_DATCAT: Joi.string().allow("", null),
      DELIV_DATE: Joi.string().allow("", null),
      DELIV_TIME: Joi.string().allow("", null),
      QUANTITY: Joi.number().allow("", null),
      PREQ_NO: Joi.string().allow("", null),
      PREQ_ITEM: Joi.number().allow("", null),
      CREATE_IND: Joi.string().allow("", null),
      QUOTA_NO: Joi.string().allow("", null),
      QUOTA_ITEM: Joi.number().allow("", null),
      BOMEXPL_NO: Joi.string().allow("", null),
      RESERV_NO: Joi.number().allow("", null),
      BATCH: Joi.string().allow("", null),
      VEND_BATCH: Joi.string().allow("", null),
      VERSION: Joi.string().allow("", null),
      DEL_DATCAT_EXT: Joi.string().allow("", null),
    })
  );

  const returnSchema = Joi.array().items(
    Joi.object({
      TYPE: Joi.string().allow("", null),
      CODE: Joi.string().allow("", null),
      MESSAGE: Joi.string().allow("", null),
      LOG_NO: Joi.string().allow("", null),
      LOG_MSG_NO: Joi.number().allow("", null),
      MESSAGE_V1: Joi.string().allow("", null),
      MESSAGE_V2: Joi.string().allow("", null),
      MESSAGE_V3: Joi.string().allow("", null),
      MESSAGE_V4: Joi.string().allow("", null),
    })
  );

  const itTaxesSchema = Joi.array().items(
    Joi.object({
      ITEM: Joi.string().allow("", null),
      TAX_CODE: Joi.string().allow("", null),
      TAX_PER: Joi.string().allow("", null),
      TEXT: Joi.string().allow("", null),
    })
  );

  const schema = Joi.object({
    PO_NUMBER: Joi.string().allow("", null),
    PO_HEADER: poHeaderSchema,
    PO_ADDRESS: poAddressSchema,
    PO_ITEMS: poItemSchema,
    PO_ITEM_SERVICES: poItemServicesSchema,
    PO_ITEM_SCHEDULES: poItemScheduleSchema,
    RETURN: returnSchema,
    IT_TAXES: itTaxesSchema,
  });

  return schema.validate(data);
};

const paginate = (data) => {
  const schema = Joi.object({
    offset: Joi.number().default(0),
    limit: Joi.number().default(50),
    sort: Joi.string().default("id"),
    order: Joi.string().valid("asc", "desc").default("desc"),
    status: Joi.string().allow("", null).default(""),
    search: Joi.string().allow("", null).default(null),
    id: Joi.number(),
  });
  return schema.validate(data);
};

const update = (data) => {
  const poHeaderSchema = Joi.object({
    PO_NUMBER: Joi.string().allow("", null),
    CO_CODE: Joi.string().allow("", null),
    DOC_CAT: Joi.string().allow("", null),
    DOC_TYPE: Joi.string().allow("", null),
    CNTRL_IND: Joi.string().allow("", null),
    DELETE_IND: Joi.string().allow("", null),
    STATUS: Joi.string().allow("", null),
    CREATED_ON: Joi.string().allow("", null),
    CREATED_BY: Joi.string().allow("", null),
    ITEM_INTVL: Joi.number().allow("", null),
    LAST_ITEM: Joi.number().allow("", null),
    VENDOR: Joi.string().allow("", null),
    LANGUAGE: Joi.string().allow("", null),
    PMNTTRMS: Joi.string().allow("", null),
    DSCNT1_TO: Joi.number().allow("", null),
    DSCNT2_TO: Joi.number().allow("", null),
    DSCNT3_TO: Joi.number().allow("", null),
    CASH_DISC1: Joi.number().allow("", null),
    CASH_DISC2: Joi.number().allow("", null),
    PURCH_ORG: Joi.string().allow("", null),
    PUR_GROUP: Joi.string().allow("", null),
    CURRENCY: Joi.string().allow("", null),
    EXCH_RATE: Joi.number().allow("", null),
    EX_RATE_FX: Joi.string().allow("", null),
    DOC_DATE: Joi.string().allow("", null),
    VPER_START: Joi.string().allow("", null),
    VPER_END: Joi.string().allow("", null),
    APPLIC_BY: Joi.string().allow("", null),
    QUOT_DEAD: Joi.string().allow("", null),
    BINDG_PER: Joi.string().allow("", null),
    WARRANTY: Joi.string().allow("", null),
    BIDINV_NO: Joi.string().allow("", null),
    QUOTATION: Joi.string().allow("", null),
    QUOT_DATE: Joi.string().allow("", null),
    REF_1: Joi.string().allow("", null),
    SALES_PERS: Joi.string().allow("", null),
    TELEPHONE: Joi.string().allow("", null),
    SUPPL_VEND: Joi.string().allow("", null),
    CUSTOMER: Joi.string().allow("", null),
    AGREEMENT: Joi.string().allow("", null),
    REJ_REASON: Joi.string().allow("", null),
    COMPL_DLV: Joi.string().allow("", null),
    GR_MESSAGE: Joi.string().allow("", null),
    SUPPL_PLNT: Joi.string().allow("", null),
    RCVG_VEND: Joi.string().allow("", null),
    INCOTERMS1: Joi.string().allow("", null),
    INCOTERMS2: Joi.string().allow("", null),
    TARGET_VAL: Joi.number().allow("", null),
    COLL_NO: Joi.string().allow("", null),
    DOC_COND: Joi.string().allow("", null),
    PROCEDURE: Joi.string().allow("", null),
    UPDATE_GRP: Joi.string().allow("", null),
    DIFF_INV: Joi.string().allow("", null),
    EXPORT_NO: Joi.string().allow("", null),
    OUR_REF: Joi.string().allow("", null),
    LOGSYSTEM: Joi.string().allow("", null),
    SUBITEMINT: Joi.number().allow("", null),
    MAST_COND: Joi.string().allow("", null),
    REL_GROUP: Joi.string().allow("", null),
    REL_STRAT: Joi.string().allow("", null),
    REL_IND: Joi.string().allow("", null),
    REL_STATUS: Joi.string().allow("", null),
    SUBJ_TO_R: Joi.string().allow("", null),
    TAXR_CNTRY: Joi.string().allow("", null),
    SCHED_IND: Joi.string().allow("", null),
    VEND_NAME: Joi.string().allow("", null),
    CURRENCY_ISO: Joi.string().allow("", null),
    EXCH_RATE_CM: Joi.number().allow("", null),
    HOLD: Joi.string().allow("", null),
  });

  const poAddressSchema = Joi.object({
    ADDRNUMBER: Joi.string().allow("", null),
    ADDRHANDLE: Joi.string().allow("", null),
    NATION: Joi.string().allow("", null),
    DATE: Joi.string().allow("", null),
    DATE_FROM: Joi.string().allow("", null),
    DATE_TO: Joi.string().allow("", null),
    TITLE: Joi.string().allow("", null),
    NAME1: Joi.string().allow("", null),
    NAME2: Joi.string().allow("", null),
    NAME3: Joi.string().allow("", null),
    NAME4: Joi.string().allow("", null),
    NAME_TXT: Joi.string().allow("", null),
    NAME_CO: Joi.string().allow("", null),
    CITY1: Joi.string().allow("", null),
    CITY2: Joi.string().allow("", null),
    CITY_CODE: Joi.string().allow("", null),
    CITYP_CODE: Joi.string().allow("", null),
    CHCKSTATUS: Joi.string().allow("", null),
    POST_CODE1: Joi.string().allow("", null),
    POST_CODE2: Joi.string().allow("", null),
    POST_CODE3: Joi.string().allow("", null),
    PO_BOX: Joi.string().allow("", null),
    PO_BOX_NUM: Joi.string().allow("", null),
    PO_BOX_LOC: Joi.string().allow("", null),
    CITY_CODE2: Joi.string().allow("", null),
    PO_BOX_REG: Joi.string().allow("", null),
    PO_BOX_CTY: Joi.string().allow("", null),
    POSTALAREA: Joi.string().allow("", null),
    TRANSPZONE: Joi.string().allow("", null),
    STREET: Joi.string().allow("", null),
    STREETCODE: Joi.string().allow("", null),
    STREETABBR: Joi.string().allow("", null),
    HOUSE_NUM1: Joi.string().allow("", null),
    HOUSE_NUM2: Joi.string().allow("", null),
    HOUSE_NUM3: Joi.string().allow("", null),
    STR_SUPPL1: Joi.string().allow("", null),
    STR_SUPPL2: Joi.string().allow("", null),
    LOCATION: Joi.string().allow("", null),
    BUILDING: Joi.string().allow("", null),
    FLOOR: Joi.string().allow("", null),
    ROOMNUMBER: Joi.string().allow("", null),
    COUNTRY: Joi.string().allow("", null),
    LANGU: Joi.string().allow("", null),
    REGION: Joi.string().allow("", null),
    SORT1: Joi.string().allow("", null),
    SORT2: Joi.string().allow("", null),
    SORT_PHN: Joi.string().allow("", null),
    ADDRORIGIN: Joi.string().allow("", null),
    EXTENSION1: Joi.string().allow("", null),
    EXTENSION2: Joi.string().allow("", null),
    TIME_ZONE: Joi.string().allow("", null),
    TAXJURCODE: Joi.string().allow("", null),
    ADDRESS_ID: Joi.string().allow("", null),
    REMARK: Joi.string().allow("", null),
    DEFLT_COMM: Joi.string().allow("", null),
    TEL_NUMBER: Joi.string().allow("", null),
    TEL_EXTENS: Joi.string().allow("", null),
    FAX_NUMBER: Joi.string().allow("", null),
    FAX_EXTENS: Joi.string().allow("", null),
    BUILD_LONG: Joi.string().allow("", null),
  });

  const poItemSchema = Joi.array().items(
    Joi.object({
      PO_NUMBER: Joi.string().allow("", null),
      PO_ITEM: Joi.number().allow("", null),
      DELETE_IND: Joi.string().allow("", null),
      STATUS: Joi.string().allow("", null),
      CHANGED_ON: Joi.string().allow("", null),
      SHORT_TEXT: Joi.string().allow("", null),
      MATERIAL: Joi.string().allow("", null),
      PUR_MAT: Joi.string().allow("", null),
      CO_CODE: Joi.string().allow("", null),
      PLANT: Joi.string().allow("", null),
      STORE_LOC: Joi.string().allow("", null),
      TRACKINGNO: Joi.string().allow("", null),
      MAT_GRP: Joi.string().allow("", null),
      INFO_REC: Joi.string().allow("", null),
      VEND_MAT: Joi.string().allow("", null),
      TARGET_QTY: Joi.number().allow("", null),
      QUANTITY: Joi.number().allow("", null),
      UNIT: Joi.string().allow("", null),
      ORDERPR_UN: Joi.string().allow("", null),
      CONV_NUM1: Joi.number().allow("", null),
      CONV_DEN1: Joi.number().allow("", null),
      CONV_NUM2: Joi.number().allow("", null),
      CONV_DEN2: Joi.number().allow("", null),
      NET_PRICE: Joi.number().allow("", null),
      PRICE_UNIT: Joi.number().allow("", null),
      NET_VALUE: Joi.number().allow("", null),
      GROS_VALUE: Joi.number().allow("", null),
      QUOT_DEAD: Joi.string().allow("", null),
      GR_PR_TIME: Joi.number().allow("", null),
      TAX_CODE: Joi.string().allow("", null),
      SETT_GRP1: Joi.string().allow("", null),
      QUAL_INSP: Joi.string().allow("", null),
      INFO_UPD: Joi.string().allow("", null),
      PRNT_PRICE: Joi.string().allow("", null),
      EST_PRICE: Joi.string().allow("", null),
      NUM_REMIND: Joi.number().allow("", null),
      REMINDER1: Joi.number().allow("", null),
      REMINDER2: Joi.number().allow("", null),
      REMINDER3: Joi.number().allow("", null),
      OVERDELTOL: Joi.number().allow("", null),
      UNLIMITED: Joi.string().allow("", null),
      UNDER_TOL: Joi.number().allow("", null),
      VAL_TYPE: Joi.string().allow("", null),
      VAL_CAT: Joi.string().allow("", null),
      REJ_IND: Joi.string().allow("", null),
      COMMENT: Joi.string().allow("", null),
      DEL_COMPL: Joi.string().allow("", null),
      FINAL_INV: Joi.string().allow("", null),
      ITEM_CAT: Joi.string().allow("", null),
      ACCTASSCAT: Joi.string().allow("", null),
      CONSUMPT: Joi.string().allow("", null),
      DISTRIB: Joi.string().allow("", null),
      PART_INV: Joi.string().allow("", null),
      GR_IND: Joi.string().allow("", null),
      GR_NON_VAL: Joi.string().allow("", null),
      IR_IND: Joi.string().allow("", null),
      GR_BASEDIV: Joi.string().allow("", null),
      ACKN_REQD: Joi.string().allow("", null),
      ACKNOWL_NO: Joi.string().allow("", null),
      AGREEMENT: Joi.string().allow("", null),
      AGMT_ITEM: Joi.number().allow("", null),
      RECON_DATE: Joi.string().allow("", null),
      AGRCUMQTY: Joi.number().allow("", null),
      FIRM_ZONE: Joi.number().allow("", null),
      TRADE_OFF: Joi.number().allow("", null),
      BOM_EXPL: Joi.string().allow("", null),
      EXCLUSION: Joi.string().allow("", null),
      BASE_UNIT: Joi.string().allow("", null),
      SHIPPING: Joi.string().allow("", null),
      OUTL_TARGV: Joi.number().allow("", null),
      NOND_ITAX: Joi.number().allow("", null),
      RELORD_QTY: Joi.number().allow("", null),
      PRICE_DATE: Joi.string().allow("", null),
      DOC_CAT: Joi.string().allow("", null),
      EFF_VALUE: Joi.number().allow("", null),
      COMMITMENT: Joi.string().allow("", null),
      CUSTOMER: Joi.string().allow("", null),
      ADDRESS: Joi.string().allow("", null),
      COND_GROUP: Joi.string().allow("", null),
      NO_C_DISC: Joi.string().allow("", null),
      UPDATE_GRP: Joi.string().allow("", null),
      PLAN_DEL: Joi.number().allow("", null),
      NET_WEIGHT: Joi.number().allow("", null),
      WEIGHTUNIT: Joi.string().allow("", null),
      TAX_JUR_CD: Joi.string().allow("", null),
      PRINT_REL: Joi.string().allow("", null),
      SPEC_STOCK: Joi.string().allow("", null),
      SETRESERNO: Joi.number().allow("", null),
      SETTLITMNO: Joi.number().allow("", null),
      NOT_CHGBL: Joi.string().allow("", null),
      CTR_KEY_QM: Joi.string().allow("", null),
      CERT_TYPE: Joi.string().allow("", null),
      EAN_UPC: Joi.string().allow("", null),
      CONF_CTRL: Joi.string().allow("", null),
      REV_LEV: Joi.string().allow("", null),
      FUND: Joi.string().allow("", null),
      FUNDS_CTR: Joi.string().allow("", null),
      CMMT_ITEM: Joi.string().allow("", null),
      BA_PARTNER: Joi.string().allow("", null),
      PTR_ASS_BA: Joi.string().allow("", null),
      PROFIT_CTR: Joi.string().allow("", null),
      PARTNER_PC: Joi.string().allow("", null),
      PRICE_CTR: Joi.string().allow("", null),
      GROSS_WGHT: Joi.number().allow("", null),
      VOLUME: Joi.number().allow("", null),
      VOLUMEUNIT: Joi.string().allow("", null),
      INCOTERMS1: Joi.string().allow("", null),
      INCOTERMS2: Joi.string().allow("", null),
      ADVANCE: Joi.string().allow("", null),
      PRIOR_VEND: Joi.string().allow("", null),
      SUB_RANGE: Joi.string().allow("", null),
      PCKG_NO: Joi.number().allow("", null),
      STATISTIC: Joi.string().allow("", null),
      HL_ITEM: Joi.number().allow("", null),
      GR_TO_DATE: Joi.string().allow("", null),
      SUPPL_VEND: Joi.string().allow("", null),
      SC_VENDOR: Joi.string().allow("", null),
      CONF_MATL: Joi.string().allow("", null),
      MAT_CAT: Joi.string().allow("", null),
      KANBAN_IND: Joi.string().allow("", null),
      ADDRESS2: Joi.string().allow("", null),
      INT_OBJ_NO: Joi.number().allow("", null),
      ERS: Joi.string().allow("", null),
      GRSETTFROM: Joi.string().allow("", null),
      LAST_TRANS: Joi.string().allow("", null),
      TRANS_TIME: Joi.string().allow("", null),
      SER_NO: Joi.number().allow("", null),
      PROMOTION: Joi.string().allow("", null),
      ALLOC_TBL: Joi.string().allow("", null),
      AT_ITEM: Joi.number().allow("", null),
      POINTS: Joi.number().allow("", null),
      POINTS_UN: Joi.string().allow("", null),
      SEASON_TY: Joi.string().allow("", null),
      SEASON_YR: Joi.string().allow("", null),
      SETT_GRP_2: Joi.string().allow("", null),
      SETT_GRP_3: Joi.string().allow("", null),
      SETT_ITEM: Joi.string().allow("", null),
      ML_AKT: Joi.string().allow("", null),
      REMSHLIFE: Joi.number().allow("", null),
      RFQ: Joi.string().allow("", null),
      RFQ_ITEM: Joi.number().allow("", null),
      CONFIG_ORG: Joi.string().allow("", null),
      QUOTAUSAGE: Joi.string().allow("", null),
      SPSTCK_PHY: Joi.string().allow("", null),
      PREQ_NO: Joi.string().allow("", null),
      PREQ_ITEM: Joi.number().allow("", null),
      MAT_TYPE: Joi.string().allow("", null),
      SI_CAT: Joi.string().allow("", null),
      SUB_ITEMS: Joi.string().allow("", null),
      SUBTOTAL_1: Joi.number().allow("", null),
      SUBTOTAL_2: Joi.number().allow("", null),
      SUBTOTAL_3: Joi.number().allow("", null),
      SUBTOTAL_4: Joi.number().allow("", null),
      SUBTOTAL_5: Joi.number().allow("", null),
      SUBTOTAL_6: Joi.number().allow("", null),
      SUBITM_KEY: Joi.string().allow("", null),
      MAX_CMG: Joi.number().allow("", null),
      MAX_CPGO: Joi.number().allow("", null),
      RET_ITEM: Joi.string().allow("", null),
      AT_RELEV: Joi.string().allow("", null),
      ORD_REAS: Joi.string().allow("", null),
      DEL_TYP_RT: Joi.string().allow("", null),
      PRDTE_CTRL: Joi.string().allow("", null),
      MANUF_PROF: Joi.string().allow("", null),
      MANU_MAT: Joi.string().allow("", null),
      MFR_NO: Joi.string().allow("", null),
      MFR_NO_EXT: Joi.string().allow("", null),
      ITEM_CAT_EXT: Joi.string().allow("", null),
      PO_UNIT_ISO: Joi.string().allow("", null),
      ORDERPR_UN_ISO: Joi.string().allow("", null),
      BASE_UOM_ISO: Joi.string().allow("", null),
      WEIGHTUNIT_ISO: Joi.string().allow("", null),
      VOLUMEUNIT_ISO: Joi.string().allow("", null),
      POINTS_UN_ISO: Joi.string().allow("", null),
      CONF_MATL_EXTERNAL: Joi.string().allow("", null),
      CONF_MATL_GUID: Joi.string().allow("", null),
      CONF_MATL_VERSION: Joi.string().allow("", null),
      MATERIAL_EXTERNAL: Joi.string().allow("", null),
      MATERIAL_GUID: Joi.string().allow("", null),
      MATERIAL_VERSION: Joi.string().allow("", null),
      PUR_MAT_EXTERNAL: Joi.string().allow("", null),
      PUR_MAT_GUID: Joi.string().allow("", null),
      PUR_MAT_VERSION: Joi.string().allow("", null),
      GRANT_NBR: Joi.string().allow("", null),
      CMMT_ITEM_LONG: Joi.string().allow("", null),
      FUNC_AREA_LONG: Joi.string().allow("", null),
      BUDGET_PERIOD: Joi.string().allow("", null),
      MATERIAL_LONG: Joi.string().allow("", null),
      PUR_MAT_LONG: Joi.string().allow("", null),
      CONF_MATL_LONG: Joi.string().allow("", null),
      ORIGINAL_QUANTITY: Joi.number().allow("", null),
    })
  );

  const poItemServicesSchema = Joi.array().items(
    Joi.object({
      PCKG_NO: Joi.number().allow("", null),
      LINE_NO: Joi.number().allow("", null),
      EXT_LINE: Joi.number().allow("", null),
      OUTL_LEVEL: Joi.number().allow("", null),
      OUTL_NO: Joi.string().allow("", null),
      OUTL_IND: Joi.string().allow("", null),
      SUBPCKG_NO: Joi.number().allow("", null),
      DELETE_IND: Joi.string().allow("", null),
      SERVICE: Joi.string().allow("", null),
      SERV_TYPE: Joi.string().allow("", null),
      EDITION: Joi.number().allow("", null),
      SSC_ITEM: Joi.string().allow("", null),
      EXT_SERV: Joi.string().allow("", null),
      QUANTITY: Joi.number().allow("", null),
      BASE_UOM: Joi.string().allow("", null),
      UOM_ISO: Joi.string().allow("", null),
      OVF_TOL: Joi.number().allow("", null),
      OVF_UNLIM: Joi.string().allow("", null),
      PRICE_UNIT: Joi.number().allow("", null),
      GROSS_VAL: Joi.number().allow("", null),
      NET_VALUE: Joi.number().allow("", null),
      FROM_LINE: Joi.string().allow("", null),
      TO_LINE: Joi.string().allow("", null),
      SHORT_TEXT: Joi.string().allow("", null),
      DISTRIB: Joi.string().allow("", null),
      PERS_NO: Joi.number().allow("", null),
      WAGETYPE: Joi.string().allow("", null),
      PLN_PCKG: Joi.number().allow("", null),
      PLN_LINE: Joi.number().allow("", null),
      CON_PCKG: Joi.number().allow("", null),
      CON_LINE: Joi.number().allow("", null),
      TMP_PCKG: Joi.number().allow("", null),
      TMP_LINE: Joi.number().allow("", null),
      SSC_LIM: Joi.string().allow("", null),
      LIMIT_LINE: Joi.number().allow("", null),
      ACTUAL_QTY: Joi.number().allow("", null),
      ACTUAL_VAL: Joi.number().allow("", null),
      CON_VALUE: Joi.number().allow("", null),
      CON_QTY: Joi.number().allow("", null),
      TARGET_VAL: Joi.number().allow("", null),
      UNPL_VAL: Joi.number().allow("", null),
      UNPL_QTY: Joi.number().allow("", null),
      BASLINE_NO: Joi.number().allow("", null),
      BASIC_LINE: Joi.string().allow("", null),
      ALTERNAT: Joi.string().allow("", null),
      BIDDER: Joi.string().allow("", null),
      SUPP_LINE: Joi.string().allow("", null),
      OPEN_QTY: Joi.string().allow("", null),
      INFORM: Joi.string().allow("", null),
      BLANKET: Joi.string().allow("", null),
      EVENTUAL: Joi.string().allow("", null),
      TAX_CODE: Joi.string().allow("", null),
      TAXJURCODE: Joi.string().allow("", null),
      PRICE_CHG: Joi.string().allow("", null),
      MATL_GROUP: Joi.string().allow("", null),
      NOND_ITAX: Joi.number().allow("", null),
      DATE: Joi.string().allow("", null),
      BEGINTIME: Joi.string().allow("", null),
      ENDTIME: Joi.string().allow("", null),
      EXTPERS_NO: Joi.string().allow("", null),
      FORMULA: Joi.string().allow("", null),
      FORM_VAL1: Joi.number().allow("", null),
      FORM_VAL2: Joi.number().allow("", null),
      FORM_VAL3: Joi.number().allow("", null),
      FORM_VAL4: Joi.number().allow("", null),
      FORM_VAL5: Joi.number().allow("", null),
      USERF1_NUM: Joi.number().allow("", null),
      USERF2_NUM: Joi.number().allow("", null),
      USERF1_TXT: Joi.string().allow("", null),
      USERF2_TXT: Joi.string().allow("", null),
      GR_PRICE: Joi.number().allow("", null),
      HI_LINE_NO: Joi.number().allow("", null),
      EXTREFKEY: Joi.string().allow("", null),
      PER_SDATE: Joi.string().allow("", null),
      PER_EDATE: Joi.string().allow("", null),
      EXTERNAL_ITEM_ID: Joi.string().allow("", null),
      SERVICE_ITEM_KEY: Joi.number().allow("", null),
      ORIGINAL_QUANTITY: Joi.number().allow("", null),
    })
  );

  const poItemScheduleSchema = Joi.array().items(
    Joi.object({
      PO_ITEM: Joi.number().allow("", null),
      SERIAL_NO: Joi.number().allow("", null),
      DEL_DATCAT: Joi.string().allow("", null),
      DELIV_DATE: Joi.string().allow("", null),
      DELIV_TIME: Joi.string().allow("", null),
      QUANTITY: Joi.number().allow("", null),
      PREQ_NO: Joi.string().allow("", null),
      PREQ_ITEM: Joi.number().allow("", null),
      CREATE_IND: Joi.string().allow("", null),
      QUOTA_NO: Joi.string().allow("", null),
      QUOTA_ITEM: Joi.number().allow("", null),
      BOMEXPL_NO: Joi.string().allow("", null),
      RESERV_NO: Joi.number().allow("", null),
      BATCH: Joi.string().allow("", null),
      VEND_BATCH: Joi.string().allow("", null),
      VERSION: Joi.string().allow("", null),
      DEL_DATCAT_EXT: Joi.string().allow("", null),
    })
  );

  const returnSchema = Joi.array().items(
    Joi.object({
      TYPE: Joi.string().allow("", null),
      CODE: Joi.string().allow("", null),
      MESSAGE: Joi.string().allow("", null),
      LOG_NO: Joi.string().allow("", null),
      LOG_MSG_NO: Joi.number().allow("", null),
      MESSAGE_V1: Joi.string().allow("", null),
      MESSAGE_V2: Joi.string().allow("", null),
      MESSAGE_V3: Joi.string().allow("", null),
      MESSAGE_V4: Joi.string().allow("", null),
    })
  );

  const itTaxesSchema = Joi.array().items(
    Joi.object({
      ITEM: Joi.string().allow("", null),
      TAX_CODE: Joi.string().allow("", null),
      TAX_PER: Joi.string().allow("", null),
      TEXT: Joi.string().allow("", null),
    })
  );

  const schema = Joi.object({
    PO_NUMBER: Joi.string().allow("", null),
    PO_HEADER: poHeaderSchema,
    PO_ADDRESS: poAddressSchema,
    PO_ITEMS: poItemSchema,
    PO_ITEM_SERVICES: poItemServicesSchema,
    PO_ITEM_SCHEDULES: poItemScheduleSchema,
    RETURN: returnSchema,
    IT_TAXES: itTaxesSchema,
  });
  return schema.validate(data);
};

const del = (data) => {
  const schema = Joi.object({
    id: Joi.number().required(),
  });
  return schema.validate(data);
};

const view = (data) => {
  const schema = Joi.object({
    id: Joi.number().required(),
  });
  return schema.validate(data);
};
export default {
  create,
  paginate,
  update,
  del,
  view,
};
