/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex("apis").del();
  await knex("apis").insert([
    {
      id: 1,
      name: "masterindia",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 2,
      name: "masterIndiaCreds",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 3,
      name: "sandBox",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 4,
      name: "msmeKey",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 5,
      name: "bankAccKey",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 6,
      name: "sandbox-irn",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 7,
      name: "sandbox-auth",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 8,
      name: "sandbox-otp",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 9,
      name: "sandbox-authenticateUser",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 10,
      name: "sandbox-verifygstin",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 11,
      name: "sandbox-ewayAuth",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 12,
      name: "sandbox-ewayBill",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 13,
      name: "sandbox-fetchInvoice",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 14,
      name: "surepass_send_otp_for_msme",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 15,
      name: "surepass_submit_otp_for_msme",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 16,
      name: "surepass_get_msme_details",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
    {
      id: 17,
      name: "surepass_get_bank_details",
      username: null,
      password: null,
      clientId: null,
      clientSecret: null,
      grantType: null,
      apiKey: null,
      secretKey: null,
      url: null,
      authorization: null,
      apiVersion: null,
      status: "1",
      modifiedBy: null,
    },
  ]);
}
