/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex('countries').del()
  await knex('countries').insert([
    {
      id: 1,
      country_id: 228,
      capital: "Funafuti",
      currency_code: 228,
      domain: ".tv",
      emoji: "????????",
      country_key: "TV",
      iso3: "TUV",
      latitude: "'-8",
      longitude: "178",
      name: "Tuvalu",
      native: "Tuvalu",
      phonecode: "688",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 2,
      country_id: 99,
      capital: "Budapest",
      currency_code: 99,
      domain: ".hu",
      emoji: "????????",
      country_key: "HU",
      iso3: "HUN",
      latitude: "47",
      longitude: "20",
      name: "Hungary",
      native: "Magyarország",
      phonecode: "36",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 3,
      country_id: 63,
      capital: "Dili",
      currency_code: 63,
      domain: ".tl",
      emoji: "????????",
      country_key: "TL",
      iso3: "TLS",
      latitude: "'-8.83333333",
      longitude: "125.91666666",
      name: "East Timor",
      native: "Timor-Leste",
      phonecode: "670",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 4,
      country_id: 141,
      capital: "Mamoudzou",
      currency_code: 141,
      domain: ".yt",
      emoji: "????????",
      country_key: "YT",
      iso3: "MYT",
      latitude: "'-12.83333333",
      longitude: "45.16666666",
      name: "Mayotte",
      native: "Mayotte",
      phonecode: "262",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 5,
      country_id: 207,
      capital: "Madrid",
      currency_code: 207,
      domain: ".es",
      emoji: "????????",
      country_key: "ES",
      iso3: "ESP",
      latitude: "40",
      longitude: "'-4",
      name: "Spain",
      native: "España",
      phonecode: "34",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 6,
      country_id: 195,
      capital: "Dakar",
      currency_code: 195,
      domain: ".sn",
      emoji: "????????",
      country_key: "SN",
      iso3: "SEN",
      latitude: "14",
      longitude: "'-14",
      name: "Senegal",
      native: "Sénégal",
      phonecode: "221",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 7,
      country_id: 92,
      capital: "Conakry",
      currency_code: 92,
      domain: ".gn",
      emoji: "????????",
      country_key: "GN",
      iso3: "GIN",
      latitude: "11",
      longitude: "'-10",
      name: "Guinea",
      native: "Guinée",
      phonecode: "224",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 8,
      country_id: 120,
      capital: "Riga",
      currency_code: 120,
      domain: ".lv",
      emoji: "????????",
      country_key: "LV",
      iso3: "LVA",
      latitude: "57",
      longitude: "25",
      name: "Latvia",
      native: "Latvija",
      phonecode: "371",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 9,
      country_id: 231,
      capital: "Abu Dhabi",
      currency_code: 231,
      domain: ".ae",
      emoji: "????????",
      country_key: "AE",
      iso3: "ARE",
      latitude: "24",
      longitude: "54",
      name: "United Arab Emirates",
      native: "دولة الإمارات العربية المتحدة",
      phonecode: "971",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 10,
      country_id: 168,
      capital: "Melekeok",
      currency_code: 168,
      domain: ".pw",
      emoji: "????????",
      country_key: "PW",
      iso3: "PLW",
      latitude: "7.5",
      longitude: "134.5",
      name: "Palau",
      native: "Palau",
      phonecode: "680",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 11,
      country_id: 64,
      capital: "Quito",
      currency_code: 64,
      domain: ".ec",
      emoji: "????????",
      country_key: "EC",
      iso3: "ECU",
      latitude: "'-2",
      longitude: "'-77.5",
      name: "Ecuador",
      native: "Ecuador",
      phonecode: "593",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 12,
      country_id: 103,
      capital: "Tehran",
      currency_code: 103,
      domain: ".ir",
      emoji: "????????",
      country_key: "IR",
      iso3: "IRN",
      latitude: "32",
      longitude: "53",
      name: "Iran",
      native: "ایران",
      phonecode: "98",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 13,
      country_id: 242,
      capital: "Charlotte Amalie",
      currency_code: 242,
      domain: ".vi",
      emoji: "????????",
      country_key: "VI",
      iso3: "VIR",
      latitude: "18.34",
      longitude: "'-64.93",
      name: "Virgin Islands (US)",
      native: "United States Virgin Islands",
      phonecode: "'+1-340",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 14,
      country_id: 102,
      capital: "Jakarta",
      currency_code: 102,
      domain: ".id",
      emoji: "????????",
      country_key: "DL",
      iso3: "IDN",
      latitude: "'-5",
      longitude: "120",
      name: "Indonesia",
      native: "Indonesia",
      phonecode: "62",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 15,
      country_id: 204,
      capital: "Pretoria",
      currency_code: 204,
      domain: ".za",
      emoji: "????????",
      country_key: "ZA",
      iso3: "ZAF",
      latitude: "'-29",
      longitude: "24",
      name: "South Africa",
      native: "South Africa",
      phonecode: "27",
      region: "Africa",
      subregion: "Southern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 16,
      country_id: 36,
      capital: "Bujumbura",
      currency_code: 36,
      domain: ".bi",
      emoji: "????????",
      country_key: "BI",
      iso3: "BDI",
      latitude: "'-3.5",
      longitude: "30",
      name: "Burundi",
      native: "Burundi",
      phonecode: "257",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 17,
      country_id: 49,
      capital: "Moroni",
      currency_code: 49,
      domain: ".km",
      emoji: "????????",
      country_key: "KM",
      iso3: "COM",
      latitude: "'-12.16666666",
      longitude: "44.25",
      name: "Comoros",
      native: "Komori",
      phonecode: "269",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 18,
      country_id: 167,
      capital: "Islamabad",
      currency_code: 167,
      domain: ".pk",
      emoji: "????????",
      country_key: "PK",
      iso3: "PAK",
      latitude: "30",
      longitude: "70",
      name: "Pakistan",
      native: "Pakistan",
      phonecode: "92",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 19,
      country_id: 147,
      capital: "Podgorica",
      currency_code: 147,
      domain: ".me",
      emoji: "????????",
      country_key: "ME",
      iso3: "MNE",
      latitude: "42.5",
      longitude: "19.3",
      name: "Montenegro",
      native: "Црна Гора",
      phonecode: "382",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 20,
      country_id: 33,
      capital: "Bandar Seri Begawan",
      currency_code: 33,
      domain: ".bn",
      emoji: "????????",
      country_key: "BN",
      iso3: "BRN",
      latitude: "4.5",
      longitude: "114.66666666",
      name: "Brunei",
      native: "Negara Brunei Darussalam",
      phonecode: "673",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 21,
      country_id: 186,
      capital: "Castries",
      currency_code: 186,
      domain: ".lc",
      emoji: "????????",
      country_key: "LC",
      iso3: "LCA",
      latitude: "13.88333333",
      longitude: "'-60.96666666",
      name: "Saint Lucia",
      native: "Saint Lucia",
      phonecode: "'+1-758",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 22,
      country_id: 22,
      capital: "Brussels",
      currency_code: 22,
      domain: ".be",
      emoji: "????????",
      country_key: "BE",
      iso3: "BEL",
      latitude: "50.83333333",
      longitude: "4",
      name: "Belgium",
      native: "België",
      phonecode: "32",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 23,
      country_id: 172,
      capital: "Asuncion",
      currency_code: 172,
      domain: ".py",
      emoji: "????????",
      country_key: "PY",
      iso3: "PRY",
      latitude: "'-23",
      longitude: "'-58",
      name: "Paraguay",
      native: "Paraguay",
      phonecode: "595",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 24,
      country_id: 139,
      capital: "Nouakchott",
      currency_code: 139,
      domain: ".mr",
      emoji: "????????",
      country_key: "MR",
      iso3: "MRT",
      latitude: "20",
      longitude: "'-12",
      name: "Mauritania",
      native: "موريتانيا",
      phonecode: "222",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 25,
      country_id: 18,
      capital: "Manama",
      currency_code: 18,
      domain: ".bh",
      emoji: "????????",
      country_key: "BH",
      iso3: "BHR",
      latitude: "26",
      longitude: "50.55",
      name: "Bahrain",
      native: "‏البحرين",
      phonecode: "973",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 26,
      country_id: 50,
      capital: "Brazzaville",
      currency_code: 50,
      domain: ".cg",
      emoji: "????????",
      country_key: "CG",
      iso3: "COG",
      latitude: "'-1",
      longitude: "15",
      name: "Congo",
      native: "République du Congo",
      phonecode: "242",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 27,
      country_id: 191,
      capital: "Apia",
      currency_code: 191,
      domain: ".ws",
      emoji: "????????",
      country_key: "WS",
      iso3: "WSM",
      latitude: "'-13.58333333",
      longitude: "'-172.33333333",
      name: "Samoa",
      native: "Samoa",
      phonecode: "685",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 28,
      country_id: 174,
      capital: "Manila",
      currency_code: 174,
      domain: ".ph",
      emoji: "????????",
      country_key: "PH",
      iso3: "PHL",
      latitude: "13",
      longitude: "122",
      name: "Philippines",
      native: "Pilipinas",
      phonecode: "63",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 29,
      country_id: 109,
      capital: "Tokyo",
      currency_code: 109,
      domain: ".jp",
      emoji: "????????",
      country_key: "JP",
      iso3: "JPN",
      latitude: "36",
      longitude: "138",
      name: "Japan",
      native: "日本",
      phonecode: "81",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 30,
      country_id: 156,
      capital: "Amsterdam",
      currency_code: 156,
      domain: ".nl",
      emoji: "????????",
      country_key: "NL",
      iso3: "NLD",
      latitude: "52.5",
      longitude: "5.75",
      name: "Netherlands The",
      native: "Nederland",
      phonecode: "31",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 31,
      country_id: 230,
      capital: "Kiev",
      currency_code: 230,
      domain: ".ua",
      emoji: "????????",
      country_key: "UA",
      iso3: "UKR",
      latitude: "49",
      longitude: "32",
      name: "Ukraine",
      native: "Україна",
      phonecode: "380",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 32,
      country_id: 16,
      capital: "Baku",
      currency_code: 16,
      domain: ".az",
      emoji: "????????",
      country_key: "AZ",
      iso3: "AZE",
      latitude: "40.5",
      longitude: "47.5",
      name: "Azerbaijan",
      native: "Azərbaycan",
      phonecode: "994",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 33,
      country_id: 40,
      capital: "Praia",
      currency_code: 40,
      domain: ".cv",
      emoji: "????????",
      country_key: "CV",
      iso3: "CPV",
      latitude: "16",
      longitude: "'-24",
      name: "Cape Verde",
      native: "Cabo Verde",
      phonecode: "238",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 34,
      country_id: 90,
      capital: "Guatemala City",
      currency_code: 90,
      domain: ".gt",
      emoji: "????????",
      country_key: "GT",
      iso3: "GTM",
      latitude: "15.5",
      longitude: "'-90.25",
      name: "Guatemala",
      native: "Guatemala",
      phonecode: "502",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 35,
      country_id: 2,
      capital: "Mariehamn",
      currency_code: 2,
      domain: ".ax",
      emoji: "????????",
      country_key: "AX",
      iso3: "ALA",
      latitude: "60.116667",
      longitude: "19.9",
      name: "Aland Islands",
      native: "Åland",
      phonecode: "'+358-18",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 36,
      country_id: 237,
      capital: "Port Vila",
      currency_code: 237,
      domain: ".vu",
      emoji: "????????",
      country_key: "VU",
      iso3: "VUT",
      latitude: "'-16",
      longitude: "167",
      name: "Vanuatu",
      native: "Vanuatu",
      phonecode: "678",
      region: "Oceania",
      subregion: "Melanesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 37,
      country_id: 135,
      capital: "Valletta",
      currency_code: 135,
      domain: ".mt",
      emoji: "????????",
      country_key: "MT",
      iso3: "MLT",
      latitude: "35.83333333",
      longitude: "14.58333333",
      name: "Malta",
      native: "Malta",
      phonecode: "356",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 38,
      country_id: 104,
      capital: "Baghdad",
      currency_code: 104,
      domain: ".iq",
      emoji: "????????",
      country_key: "IQ",
      iso3: "IRQ",
      latitude: "33",
      longitude: "44",
      name: "Iraq",
      native: "العراق",
      phonecode: "964",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 39,
      country_id: 13,
      capital: "Oranjestad",
      currency_code: 13,
      domain: ".aw",
      emoji: "????????",
      country_key: "AW",
      iso3: "ABW",
      latitude: "12.5",
      longitude: "'-69.96666666",
      name: "Aruba",
      native: "Aruba",
      phonecode: "297",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 40,
      country_id: 121,
      capital: "Beirut",
      currency_code: 121,
      domain: ".lb",
      emoji: "????????",
      country_key: "LB",
      iso3: "LBN",
      latitude: "33.83333333",
      longitude: "35.83333333",
      name: "Lebanon",
      native: "لبنان",
      phonecode: "961",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 41,
      country_id: 198,
      capital: "Freetown",
      currency_code: 198,
      domain: ".sl",
      emoji: "????????",
      country_key: "SL",
      iso3: "SLE",
      latitude: "8.5",
      longitude: "'-11.5",
      name: "Sierra Leone",
      native: "Sierra Leone",
      phonecode: "232",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 42,
      country_id: 54,
      capital: "Yamoussoukro",
      currency_code: 54,
      domain: ".ci",
      emoji: "????????",
      country_key: "CI",
      iso3: "CIV",
      latitude: "8",
      longitude: "'-5",
      name: "Cote D'Ivoire (Ivory Coast)",
      native: "",
      phonecode: "225",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 43,
      country_id: 189,
      capital: "Gustavia",
      currency_code: 189,
      domain: ".bl",
      emoji: "????????",
      country_key: "BL",
      iso3: "BLM",
      latitude: "18.5",
      longitude: "'-63.41666666",
      name: "Saint-Barthelemy",
      native: "Saint-Barthélemy",
      phonecode: "590",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 44,
      country_id: 79,
      capital: "Libreville",
      currency_code: 79,
      domain: ".ga",
      emoji: "????????",
      country_key: "GA",
      iso3: "GAB",
      latitude: "'-1",
      longitude: "11.75",
      name: "Gabon",
      native: "Gabon",
      phonecode: "241",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 45,
      country_id: 249,
      capital: "Willemstad",
      currency_code: 249,
      domain: ".cw",
      emoji: "????????",
      country_key: "CW",
      iso3: "CUW",
      latitude: "12.116667",
      longitude: "'-68.933333",
      name: "Curaçao",
      native: "Curaçao",
      phonecode: "599",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 46,
      country_id: 8,
      capital: "The Valley",
      currency_code: 8,
      domain: ".ai",
      emoji: "????????",
      country_key: "AI",
      iso3: "AIA",
      latitude: "18.25",
      longitude: "'-63.16666666",
      name: "Anguilla",
      native: "Anguilla",
      phonecode: "'+1-264",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 47,
      country_id: 240,
      capital: "Hanoi",
      currency_code: 240,
      domain: ".vn",
      emoji: "????????",
      country_key: "VN",
      iso3: "VNM",
      latitude: "16.16666666",
      longitude: "107.83333333",
      name: "Vietnam",
      native: "Việt Nam",
      phonecode: "84",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 48,
      country_id: 66,
      capital: "San Salvador",
      currency_code: 66,
      domain: ".sv",
      emoji: "????????",
      country_key: "SV",
      iso3: "SLV",
      latitude: "13.83333333",
      longitude: "'-88.91666666",
      name: "El Salvador",
      native: "El Salvador",
      phonecode: "503",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 49,
      country_id: 170,
      capital: "Panama City",
      currency_code: 170,
      domain: ".pa",
      emoji: "????????",
      country_key: "PA",
      iso3: "PAN",
      latitude: "9",
      longitude: "'-80",
      name: "Panama",
      native: "Panamá",
      phonecode: "507",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 50,
      country_id: 108,
      capital: "Kingston",
      currency_code: 108,
      domain: ".jm",
      emoji: "????????",
      country_key: "JM",
      iso3: "JAM",
      latitude: "18.25",
      longitude: "'-77.5",
      name: "Jamaica",
      native: "Jamaica",
      phonecode: "'+1-876",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 51,
      country_id: 194,
      capital: "Riyadh",
      currency_code: 194,
      domain: ".sa",
      emoji: "????????",
      country_key: "SA",
      iso3: "SAU",
      latitude: "25",
      longitude: "45",
      name: "Saudi Arabia",
      native: "العربية السعودية",
      phonecode: "966",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 52,
      country_id: 115,
      capital: "Pyongyang",
      currency_code: 115,
      domain: ".kp",
      emoji: "????????",
      country_key: "KP",
      iso3: "PRK",
      latitude: "40",
      longitude: "127",
      name: "Korea North",
      native: "북한",
      phonecode: "850",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 53,
      country_id: 131,
      capital: "Lilongwe",
      currency_code: 131,
      domain: ".mw",
      emoji: "????????",
      country_key: "MW",
      iso3: "MWI",
      latitude: "'-13.5",
      longitude: "34",
      name: "Malawi",
      native: "Malawi",
      phonecode: "265",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 54,
      country_id: 48,
      capital: "Bogota",
      currency_code: 48,
      domain: ".co",
      emoji: "????????",
      country_key: "CO",
      iso3: "COL",
      latitude: "4",
      longitude: "'-72",
      name: "Colombia",
      native: "Colombia",
      phonecode: "57",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 55,
      country_id: 142,
      capital: "Mexico City",
      currency_code: 142,
      domain: ".mx",
      emoji: "????????",
      country_key: "MX",
      iso3: "MEX",
      latitude: "23",
      longitude: "'-102",
      name: "Mexico",
      native: "México",
      phonecode: "52",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 56,
      country_id: 9,
      capital: "",
      currency_code: 9,
      domain: ".aq",
      emoji: "????????",
      country_key: "AQ",
      iso3: "ATA",
      latitude: "'-74.65",
      longitude: "4.48",
      name: "Antarctica",
      native: "Antarctica",
      phonecode: "",
      region: "Polar",
      subregion: "",
      status: "1",
      modifiedBy: null
  },
  {
      id: 57,
      country_id: 118,
      capital: "Bishkek",
      currency_code: 118,
      domain: ".kg",
      emoji: "????????",
      country_key: "KG",
      iso3: "KGZ",
      latitude: "41",
      longitude: "75",
      name: "Kyrgyzstan",
      native: "Кыргызстан",
      phonecode: "996",
      region: "Asia",
      subregion: "Central Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 58,
      country_id: 59,
      capital: "Copenhagen",
      currency_code: 59,
      domain: ".dk",
      emoji: "????????",
      country_key: "DK",
      iso3: "DNK",
      latitude: "56",
      longitude: "10",
      name: "Denmark",
      native: "Danmark",
      phonecode: "45",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 59,
      country_id: 222,
      capital: "Nuku'alofa",
      currency_code: 222,
      domain: ".to",
      emoji: "????????",
      country_key: "TO",
      iso3: "TON",
      latitude: "'-20",
      longitude: "'-175",
      name: "Tonga",
      native: "Tonga",
      phonecode: "676",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 60,
      country_id: 106,
      capital: "Jerusalem",
      currency_code: 106,
      domain: ".il",
      emoji: "????????",
      country_key: "IL",
      iso3: "ISR",
      latitude: "31.5",
      longitude: "34.75",
      name: "Israel",
      native: "יִשְׂרָאֵל",
      phonecode: "972",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 61,
      country_id: 169,
      capital: "East Jerusalem",
      currency_code: 169,
      domain: ".ps",
      emoji: "????????",
      country_key: "PS",
      iso3: "PSE",
      latitude: "31.9",
      longitude: "35.2",
      name: "Palestinian Territory Occupied",
      native: "فلسطين",
      phonecode: "970",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 62,
      country_id: 110,
      capital: "Saint Helier",
      currency_code: 110,
      domain: ".je",
      emoji: "????????",
      country_key: "JE",
      iso3: "JEY",
      latitude: "49.25",
      longitude: "'-2.16666666",
      name: "Jersey",
      native: "Jersey",
      phonecode: "'+44-1534",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 63,
      country_id: 1,
      capital: "Kabul",
      currency_code: 1,
      domain: ".af",
      emoji: "????????",
      country_key: "AF",
      iso3: "AFG",
      latitude: "33",
      longitude: "65",
      name: "Afghanistan",
      native: "افغانستان",
      phonecode: "93",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 64,
      country_id: 202,
      capital: "Honiara",
      currency_code: 202,
      domain: ".sb",
      emoji: "????????",
      country_key: "SB",
      iso3: "SLB",
      latitude: "'-8",
      longitude: "159",
      name: "Solomon Islands",
      native: "Solomon Islands",
      phonecode: "677",
      region: "Oceania",
      subregion: "Melanesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 65,
      country_id: 136,
      capital: "\"Douglas, Isle of Man\"",
      currency_code: 136,
      domain: ".im",
      emoji: "????????",
      country_key: "IM",
      iso3: "IMN",
      latitude: "54.25",
      longitude: "'-4.5",
      name: "Man (Isle of)",
      native: "Isle of Man",
      phonecode: "'+44-1624",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 66,
      country_id: 116,
      capital: "Seoul",
      currency_code: 116,
      domain: ".kr",
      emoji: "????????",
      country_key: "KR",
      iso3: "KOR",
      latitude: "37",
      longitude: "127.5",
      name: "Korea South",
      native: "대한민국",
      phonecode: "82",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 67,
      country_id: 31,
      capital: "Brasilia",
      currency_code: 31,
      domain: ".br",
      emoji: "????????",
      country_key: "BR",
      iso3: "BRA",
      latitude: "'-10",
      longitude: "'-55",
      name: "Brazil",
      native: "Brasil",
      phonecode: "55",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 68,
      country_id: 180,
      capital: "Saint-Denis",
      currency_code: 180,
      domain: ".re",
      emoji: "????????",
      country_key: "RE",
      iso3: "REU",
      latitude: "'-21.15",
      longitude: "55.5",
      name: "Reunion",
      native: "La Réunion",
      phonecode: "262",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 69,
      country_id: 133,
      capital: "Male",
      currency_code: 133,
      domain: ".mv",
      emoji: "????????",
      country_key: "MV",
      iso3: "MDV",
      latitude: "3.25",
      longitude: "73",
      name: "Maldives",
      native: "Maldives",
      phonecode: "960",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 70,
      country_id: 80,
      capital: "Banjul",
      currency_code: 80,
      domain: ".gm",
      emoji: "????????",
      country_key: "GM",
      iso3: "GMB",
      latitude: "13.46666666",
      longitude: "'-16.56666666",
      name: "Gambia The",
      native: "Gambia",
      phonecode: "220",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 71,
      country_id: 241,
      capital: "Road Town",
      currency_code: 241,
      domain: ".vg",
      emoji: "????????",
      country_key: "VG",
      iso3: "VGB",
      latitude: "18.431383",
      longitude: "'-64.62305",
      name: "Virgin Islands (British)",
      native: "British Virgin Islands",
      phonecode: "'+1-284",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 72,
      country_id: 6,
      capital: "Andorra la Vella",
      currency_code: 6,
      domain: ".ad",
      emoji: "????????",
      country_key: "AD",
      iso3: "AND",
      latitude: "42.5",
      longitude: "1.5",
      name: "Andorra",
      native: "Andorra",
      phonecode: "376",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 73,
      country_id: 187,
      capital: "Saint-Pierre",
      currency_code: 187,
      domain: ".pm",
      emoji: "????????",
      country_key: "PM",
      iso3: "SPM",
      latitude: "46.83333333",
      longitude: "'-56.33333333",
      name: "Saint Pierre and Miquelon",
      native: "Saint-Pierre-et-Miquelon",
      phonecode: "508",
      region: "Americas",
      subregion: "Northern America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 74,
      country_id: 155,
      capital: "Kralendijk",
      currency_code: 155,
      domain: ".an",
      emoji: "????????",
      country_key: "BQ",
      iso3: "BES",
      latitude: "12.15",
      longitude: "'-68.266667",
      name: "\"Bonaire, Sint Eustatius and Saba\"",
      native: "Caribisch Nederland",
      phonecode: "599",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 75,
      country_id: 206,
      capital: "Juba",
      currency_code: 206,
      domain: ".ss",
      emoji: "????????",
      country_key: "SS",
      iso3: "SSD",
      latitude: "7",
      longitude: "30",
      name: "South Sudan",
      native: "South Sudan",
      phonecode: "211",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 76,
      country_id: 62,
      capital: "Santo Domingo",
      currency_code: 62,
      domain: ".do",
      emoji: "????????",
      country_key: "DO",
      iso3: "DOM",
      latitude: "19",
      longitude: "'-70.66666666",
      name: "Dominican Republic",
      native: "República Dominicana",
      phonecode: "'+1-809 and 1-829",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 77,
      country_id: 151,
      capital: "Nay Pyi Taw",
      currency_code: 151,
      domain: ".mm",
      emoji: "????????",
      country_key: "MM",
      iso3: "MMR",
      latitude: "22",
      longitude: "98",
      name: "Myanmar",
      native: "မြန်မာ",
      phonecode: "95",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 78,
      country_id: 105,
      capital: "Dublin",
      currency_code: 105,
      domain: ".ie",
      emoji: "????????",
      country_key: "IE",
      iso3: "IRL",
      latitude: "53",
      longitude: "'-8",
      name: "Ireland",
      native: "Éire",
      phonecode: "353",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 79,
      country_id: 87,
      capital: "St. George's",
      currency_code: 87,
      domain: ".gd",
      emoji: "????????",
      country_key: "GD",
      iso3: "GRD",
      latitude: "12.11666666",
      longitude: "'-61.66666666",
      name: "Grenada",
      native: "Grenada",
      phonecode: "'+1-473",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 80,
      country_id: 75,
      capital: "Paris",
      currency_code: 75,
      domain: ".fr",
      emoji: "????????",
      country_key: "FR",
      iso3: "FRA",
      latitude: "46",
      longitude: "2",
      name: "France",
      native: "France",
      phonecode: "33",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 81,
      country_id: 76,
      capital: "Cayenne",
      currency_code: 76,
      domain: ".gf",
      emoji: "????????",
      country_key: "GF",
      iso3: "GUF",
      latitude: "4",
      longitude: "'-53",
      name: "French Guiana",
      native: "Guyane française",
      phonecode: "594",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 82,
      country_id: 97,
      capital: "Tegucigalpa",
      currency_code: 97,
      domain: ".hn",
      emoji: "????????",
      country_key: "HN",
      iso3: "HND",
      latitude: "15",
      longitude: "'-86.5",
      name: "Honduras",
      native: "Honduras",
      phonecode: "504",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 83,
      country_id: 84,
      capital: "Gibraltar",
      currency_code: 84,
      domain: ".gi",
      emoji: "????????",
      country_key: "GI",
      iso3: "GIB",
      latitude: "36.13333333",
      longitude: "'-5.35",
      name: "Gibraltar",
      native: "Gibraltar",
      phonecode: "350",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 84,
      country_id: 60,
      capital: "Djibouti",
      currency_code: 60,
      domain: ".dj",
      emoji: "????????",
      country_key: "DJ",
      iso3: "DJI",
      latitude: "11.5",
      longitude: "43",
      name: "Djibouti",
      native: "Djibouti",
      phonecode: "253",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 85,
      country_id: 143,
      capital: "Palikir",
      currency_code: 143,
      domain: ".fm",
      emoji: "????????",
      country_key: "FM",
      iso3: "FSM",
      latitude: "6.91666666",
      longitude: "158.25",
      name: "Micronesia",
      native: "Micronesia",
      phonecode: "691",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 86,
      country_id: 117,
      capital: "Kuwait City",
      currency_code: 117,
      domain: ".kw",
      emoji: "????????",
      country_key: "KW",
      iso3: "KWT",
      latitude: "29.5",
      longitude: "45.75",
      name: "Kuwait",
      native: "الكويت",
      phonecode: "965",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 87,
      country_id: 144,
      capital: "Chisinau",
      currency_code: 144,
      domain: ".md",
      emoji: "????????",
      country_key: "MD",
      iso3: "MDA",
      latitude: "47",
      longitude: "29",
      name: "Moldova",
      native: "Moldova",
      phonecode: "373",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 88,
      country_id: 148,
      capital: "Plymouth",
      currency_code: 148,
      domain: ".ms",
      emoji: "????????",
      country_key: "MS",
      iso3: "MSR",
      latitude: "16.75",
      longitude: "'-62.2",
      name: "Montserrat",
      native: "Montserrat",
      phonecode: "'+1-664",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 89,
      country_id: 61,
      capital: "Roseau",
      currency_code: 61,
      domain: ".dm",
      emoji: "????????",
      country_key: "DM",
      iso3: "DMA",
      latitude: "15.41666666",
      longitude: "'-61.33333333",
      name: "Dominica",
      native: "Dominica",
      phonecode: "'+1-767",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 90,
      country_id: 38,
      capital: "Yaounde",
      currency_code: 38,
      domain: ".cm",
      emoji: "????????",
      country_key: "CM",
      iso3: "CMR",
      latitude: "6",
      longitude: "12",
      name: "Cameroon",
      native: "Cameroon",
      phonecode: "237",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 91,
      country_id: 28,
      capital: "Sarajevo",
      currency_code: 28,
      domain: ".ba",
      emoji: "????????",
      country_key: "BA",
      iso3: "BIH",
      latitude: "44",
      longitude: "18",
      name: "Bosnia and Herzegovina",
      native: "Bosna i Hercegovina",
      phonecode: "387",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 92,
      country_id: 89,
      capital: "Hagatna",
      currency_code: 89,
      domain: ".gu",
      emoji: "????????",
      country_key: "GU",
      iso3: "GUM",
      latitude: "13.46666666",
      longitude: "144.78333333",
      name: "Guam",
      native: "Guam",
      phonecode: "'+1-671",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 93,
      country_id: 114,
      capital: "Tarawa",
      currency_code: 114,
      domain: ".ki",
      emoji: "????????",
      country_key: "KI",
      iso3: "KIR",
      latitude: "1.41666666",
      longitude: "173",
      name: "Kiribati",
      native: "Kiribati",
      phonecode: "686",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 94,
      country_id: 94,
      capital: "Georgetown",
      currency_code: 94,
      domain: ".gy",
      emoji: "????????",
      country_key: "GY",
      iso3: "GUY",
      latitude: "5",
      longitude: "'-59",
      name: "Guyana",
      native: "Guyana",
      phonecode: "592",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 95,
      country_id: 98,
      capital: "Hong Kong",
      currency_code: 98,
      domain: ".hk",
      emoji: "????????",
      country_key: "HK",
      iso3: "HKG",
      latitude: "22.25",
      longitude: "114.16666666",
      name: "Hong Kong S.A.R.",
      native: "香港",
      phonecode: "852",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 96,
      country_id: 192,
      capital: "San Marino",
      currency_code: 192,
      domain: ".sm",
      emoji: "????????",
      country_key: "SM",
      iso3: "SMR",
      latitude: "43.76666666",
      longitude: "12.41666666",
      name: "San Marino",
      native: "San Marino",
      phonecode: "378",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 97,
      country_id: 53,
      capital: "San Jose",
      currency_code: 53,
      domain: ".cr",
      emoji: "????????",
      country_key: "CR",
      iso3: "CRI",
      latitude: "10",
      longitude: "'-84",
      name: "Costa Rica",
      native: "Costa Rica",
      phonecode: "506",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 98,
      country_id: 217,
      capital: "Dushanbe",
      currency_code: 217,
      domain: ".tj",
      emoji: "????????",
      country_key: "TJ",
      iso3: "TJK",
      latitude: "39",
      longitude: "71",
      name: "Tajikistan",
      native: "Тоҷикистон",
      phonecode: "992",
      region: "Asia",
      subregion: "Central Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 99,
      country_id: 232,
      capital: "London",
      currency_code: 232,
      domain: ".uk",
      emoji: "????????",
      country_key: "GB",
      iso3: "GBR",
      latitude: "54",
      longitude: "'-2",
      name: "United Kingdom",
      native: "United Kingdom",
      phonecode: "44",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 100,
      country_id: 130,
      capital: "Antananarivo",
      currency_code: 130,
      domain: ".mg",
      emoji: "????????",
      country_key: "MG",
      iso3: "MDG",
      latitude: "'-20",
      longitude: "47",
      name: "Madagascar",
      native: "Madagasikara",
      phonecode: "261",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 101,
      country_id: 208,
      capital: "Colombo",
      currency_code: 208,
      domain: ".lk",
      emoji: "????????",
      country_key: "LK",
      iso3: "LKA",
      latitude: "7",
      longitude: "81",
      name: "Sri Lanka",
      native: "śrī laṃkāva",
      phonecode: "94",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 102,
      country_id: 82,
      capital: "Berlin",
      currency_code: 82,
      domain: ".de",
      emoji: "????????",
      country_key: "DE",
      iso3: "DEU",
      latitude: "51",
      longitude: "9",
      name: "Germany",
      native: "Deutschland",
      phonecode: "49",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 103,
      country_id: 137,
      capital: "Majuro",
      currency_code: 137,
      domain: ".mh",
      emoji: "????????",
      country_key: "MH",
      iso3: "MHL",
      latitude: "9",
      longitude: "168",
      name: "Marshall Islands",
      native: "M̧ajeļ",
      phonecode: "692",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 104,
      country_id: 113,
      capital: "Nairobi",
      currency_code: 113,
      domain: ".ke",
      emoji: "????????",
      country_key: "KE",
      iso3: "KEN",
      latitude: "1",
      longitude: "38",
      name: "Kenya",
      native: "Kenya",
      phonecode: "254",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 105,
      country_id: 30,
      capital: "",
      currency_code: 30,
      domain: ".bv",
      emoji: "????????",
      country_key: "BV",
      iso3: "BVT",
      latitude: "'-54.43333333",
      longitude: "3.4",
      name: "Bouvet Island",
      native: "Bouvetøya",
      phonecode: "55",
      region: "",
      subregion: "",
      status: "1",
      modifiedBy: null
  },
  {
      id: 106,
      country_id: 35,
      capital: "Ouagadougou",
      currency_code: 35,
      domain: ".bf",
      emoji: "????????",
      country_key: "BF",
      iso3: "BFA",
      latitude: "13",
      longitude: "'-2",
      name: "Burkina Faso",
      native: "Burkina Faso",
      phonecode: "226",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 109,
      country_id: 24,
      capital: "Porto-Novo",
      currency_code: 24,
      domain: ".bj",
      emoji: "????????",
      country_key: "BJ",
      iso3: "BEN",
      latitude: "9.5",
      longitude: "2.25",
      name: "Benin",
      native: "Bénin",
      phonecode: "229",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 110,
      country_id: 212,
      capital: "Mbabane",
      currency_code: 212,
      domain: ".sz",
      emoji: "????????",
      country_key: "SZ",
      iso3: "SWZ",
      latitude: "'-26.5",
      longitude: "31.5",
      name: "Swaziland",
      native: "Swaziland",
      phonecode: "268",
      region: "Africa",
      subregion: "Southern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 112,
      country_id: 145,
      capital: "Monaco",
      currency_code: 145,
      domain: ".mc",
      emoji: "????????",
      country_key: "MC",
      iso3: "MCO",
      latitude: "43.73333333",
      longitude: "7.4",
      name: "Monaco",
      native: "Monaco",
      phonecode: "377",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 113,
      country_id: 107,
      capital: "Rome",
      currency_code: 107,
      domain: ".it",
      emoji: "????????",
      country_key: "IT",
      iso3: "ITA",
      latitude: "42.83333333",
      longitude: "12.83333333",
      name: "Italy",
      native: "Italia",
      phonecode: "39",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 114,
      country_id: 146,
      capital: "Ulan Bator",
      currency_code: 146,
      domain: ".mn",
      emoji: "????????",
      country_key: "MN",
      iso3: "MNG",
      latitude: "46",
      longitude: "105",
      name: "Mongolia",
      native: "Монгол улс",
      phonecode: "976",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 115,
      country_id: 179,
      capital: "Doha",
      currency_code: 179,
      domain: ".qa",
      emoji: "????????",
      country_key: "QA",
      iso3: "QAT",
      latitude: "25.5",
      longitude: "51.25",
      name: "Qatar",
      native: "قطر",
      phonecode: "974",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 116,
      country_id: 171,
      capital: "Port Moresby",
      currency_code: 171,
      domain: ".pg",
      emoji: "????????",
      country_key: "PG",
      iso3: "PNG",
      latitude: "'-6",
      longitude: "147",
      name: "Papua new Guinea",
      native: "Papua Niugini",
      phonecode: "675",
      region: "Oceania",
      subregion: "Melanesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 117,
      country_id: 201,
      capital: "Ljubljana",
      currency_code: 201,
      domain: ".si",
      emoji: "????????",
      country_key: "SI",
      iso3: "SVN",
      latitude: "46.11666666",
      longitude: "14.81666666",
      name: "Slovenia",
      native: "Slovenija",
      phonecode: "386",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 118,
      country_id: 77,
      capital: "Papeete",
      currency_code: 77,
      domain: ".pf",
      emoji: "????????",
      country_key: "PF",
      iso3: "PYF",
      latitude: "'-15",
      longitude: "'-140",
      name: "French Polynesia",
      native: "Polynésie française",
      phonecode: "689",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 119,
      country_id: 250,
      capital: "Philipsburg",
      currency_code: 250,
      domain: ".sx",
      emoji: "????????",
      country_key: "SX",
      iso3: "SXM",
      latitude: "18.033333",
      longitude: "'-63.05",
      name: "Sint Maarten (Dutch part)",
      native: "Sint Maarten",
      phonecode: "1721",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 120,
      country_id: 91,
      capital: "St Peter Port",
      currency_code: 91,
      domain: ".gg",
      emoji: "????????",
      country_key: "GG",
      iso3: "GGY",
      latitude: "49.46666666",
      longitude: "'-2.58333333",
      name: "Guernsey and Alderney",
      native: "Guernsey",
      phonecode: "'+44-1481",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 121,
      country_id: 81,
      capital: "Tbilisi",
      currency_code: 81,
      domain: ".ge",
      emoji: "????????",
      country_key: "GE",
      iso3: "GEO",
      latitude: "42",
      longitude: "43.5",
      name: "Georgia",
      native: "საქართველო",
      phonecode: "995",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 122,
      country_id: 88,
      capital: "Basse-Terre",
      currency_code: 88,
      domain: ".gp",
      emoji: "????????",
      country_key: "GP",
      iso3: "GLP",
      latitude: "16.25",
      longitude: "'-61.583333",
      name: "Guadeloupe",
      native: "Guadeloupe",
      phonecode: "590",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 124,
      country_id: 140,
      capital: "Port Louis",
      currency_code: 140,
      domain: ".mu",
      emoji: "????????",
      country_key: "MU",
      iso3: "MUS",
      latitude: "'-20.28333333",
      longitude: "57.55",
      name: "Mauritius",
      native: "Maurice",
      phonecode: "230",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 125,
      country_id: 234,
      capital: "",
      currency_code: 234,
      domain: ".us",
      emoji: "????????",
      country_key: "UM",
      iso3: "UMI",
      latitude: "",
      longitude: "",
      name: "United States Minor Outlying Islands",
      native: "United States Minor Outlying Islands",
      phonecode: "1",
      region: "Americas",
      subregion: "Northern America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 126,
      country_id: 27,
      capital: "Sucre",
      currency_code: 27,
      domain: ".bo",
      emoji: "????????",
      country_key: "BO",
      iso3: "BOL",
      latitude: "'-17",
      longitude: "'-65",
      name: "Bolivia",
      native: "Bolivia",
      phonecode: "591",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 127,
      country_id: 96,
      capital: "",
      currency_code: 96,
      domain: ".hm",
      emoji: "????????",
      country_key: "HM",
      iso3: "HMD",
      latitude: "'-53.1",
      longitude: "72.51666666",
      name: "Heard Island and McDonald Islands",
      native: "Heard Island and McDonald Islands",
      phonecode: "",
      region: "",
      subregion: "",
      status: "1",
      modifiedBy: null
  },
  {
      id: 128,
      country_id: 224,
      capital: "Tunis",
      currency_code: 224,
      domain: ".tn",
      emoji: "????????",
      country_key: "TN",
      iso3: "TUN",
      latitude: "34",
      longitude: "9",
      name: "Tunisia",
      native: "تونس",
      phonecode: "216",
      region: "Africa",
      subregion: "Northern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 129,
      country_id: 132,
      capital: "Kuala Lumpur",
      currency_code: 132,
      domain: ".my",
      emoji: "????????",
      country_key: "MY",
      iso3: "MYS",
      latitude: "2.5",
      longitude: "112.5",
      name: "Malaysia",
      native: "Malaysia",
      phonecode: "60",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 130,
      country_id: 152,
      capital: "Windhoek",
      currency_code: 152,
      domain: ".na",
      emoji: "????????",
      country_key: "NA",
      iso3: "NAM",
      latitude: "'-22",
      longitude: "17",
      name: "Namibia",
      native: "Namibia",
      phonecode: "264",
      region: "Africa",
      subregion: "Southern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 131,
      country_id: 126,
      capital: "Vilnius",
      currency_code: 126,
      domain: ".lt",
      emoji: "????????",
      country_key: "LT",
      iso3: "LTU",
      latitude: "56",
      longitude: "24",
      name: "Lithuania",
      native: "Lietuva",
      phonecode: "370",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 132,
      country_id: 128,
      capital: "Macao",
      currency_code: 128,
      domain: ".mo",
      emoji: "????????",
      country_key: "MO",
      iso3: "MAC",
      latitude: "22.16666666",
      longitude: "113.55",
      name: "Macau S.A.R.",
      native: "澳門",
      phonecode: "853",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 133,
      country_id: 239,
      capital: "Caracas",
      currency_code: 239,
      domain: ".ve",
      emoji: "????????",
      country_key: "VE",
      iso3: "VEN",
      latitude: "8",
      longitude: "'-66",
      name: "Venezuela",
      native: "Venezuela",
      phonecode: "58",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 134,
      country_id: 71,
      capital: "Stanley",
      currency_code: 71,
      domain: ".fk",
      emoji: "????????",
      country_key: "FK",
      iso3: "FLK",
      latitude: "'-51.75",
      longitude: "'-59",
      name: "Falkland Islands",
      native: "Falkland Islands",
      phonecode: "500",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 135,
      country_id: 243,
      capital: "Mata Utu",
      currency_code: 243,
      domain: ".wf",
      emoji: "????????",
      country_key: "WF",
      iso3: "WLF",
      latitude: "'-13.3",
      longitude: "'-176.2",
      name: "Wallis And Futuna Islands",
      native: "Wallis et Futuna",
      phonecode: "681",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 136,
      country_id: 163,
      capital: "Kingston",
      currency_code: 163,
      domain: ".nf",
      emoji: "????????",
      country_key: "NF",
      iso3: "NFK",
      latitude: "'-29.03333333",
      longitude: "167.95",
      name: "Norfolk Island",
      native: "Norfolk Island",
      phonecode: "672",
      region: "Oceania",
      subregion: "Australia and New Zealand",
      status: "1",
      modifiedBy: null
  },
  {
      id: 137,
      country_id: 5,
      capital: "Pago Pago",
      currency_code: 5,
      domain: ".as",
      emoji: "????????",
      country_key: "AS",
      iso3: "ASM",
      latitude: "'-14.33333333",
      longitude: "'-170",
      name: "American Samoa",
      native: "American Samoa",
      phonecode: "'+1-684",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 138,
      country_id: 165,
      capital: "Oslo",
      currency_code: 165,
      domain: ".no",
      emoji: "????????",
      country_key: "NO",
      iso3: "NOR",
      latitude: "62",
      longitude: "10",
      name: "Norway",
      native: "Norge",
      phonecode: "47",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 140,
      country_id: 153,
      capital: "Yaren",
      currency_code: 153,
      domain: ".nr",
      emoji: "????????",
      country_key: "NR",
      iso3: "NRU",
      latitude: "'-0.53333333",
      longitude: "166.91666666",
      name: "Nauru",
      native: "Nauru",
      phonecode: "674",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 141,
      country_id: 119,
      capital: "Vientiane",
      currency_code: 119,
      domain: ".la",
      emoji: "????????",
      country_key: "LA",
      iso3: "LAO",
      latitude: "18",
      longitude: "105",
      name: "Laos",
      native: "ສປປລາວ",
      phonecode: "856",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 142,
      country_id: 4,
      capital: "Algiers",
      currency_code: 4,
      domain: ".dz",
      emoji: "????????",
      country_key: "DZ",
      iso3: "DZA",
      latitude: "28",
      longitude: "3",
      name: "Algeria",
      native: "الجزائر",
      phonecode: "213",
      region: "Africa",
      subregion: "Northern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 143,
      country_id: 175,
      capital: "Adamstown",
      currency_code: 175,
      domain: ".pn",
      emoji: "????????",
      country_key: "PN",
      iso3: "PCN",
      latitude: "'-25.06666666",
      longitude: "'-130.1",
      name: "Pitcairn Island",
      native: "Pitcairn Islands",
      phonecode: "870",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 144,
      country_id: 227,
      capital: "Cockburn Town",
      currency_code: 227,
      domain: ".tc",
      emoji: "????????",
      country_key: "TC",
      iso3: "TCA",
      latitude: "21.75",
      longitude: "'-71.58333333",
      name: "Turks And Caicos Islands",
      native: "Turks and Caicos Islands",
      phonecode: "'+1-649",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 145,
      country_id: 200,
      capital: "Bratislava",
      currency_code: 200,
      domain: ".sk",
      emoji: "????????",
      country_key: "SK",
      iso3: "SVK",
      latitude: "48.66666666",
      longitude: "19.5",
      name: "Slovakia",
      native: "Slovensko",
      phonecode: "421",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 146,
      country_id: 248,
      capital: "Pristina",
      currency_code: 248,
      domain: ".xk",
      emoji: "????????",
      country_key: "XK",
      iso3: "XKX",
      latitude: "42.5612909",
      longitude: "20.3403035",
      name: "Kosovo",
      native: "Republika e Kosovës",
      phonecode: "383",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 147,
      country_id: 44,
      capital: "Santiago",
      currency_code: 44,
      domain: ".cl",
      emoji: "????????",
      country_key: "CL",
      iso3: "CHL",
      latitude: "'-30",
      longitude: "'-71",
      name: "Chile",
      native: "Chile",
      phonecode: "56",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 148,
      country_id: 95,
      capital: "Port-au-Prince",
      currency_code: 95,
      domain: ".ht",
      emoji: "????????",
      country_key: "HT",
      iso3: "HTI",
      latitude: "19",
      longitude: "'-72.41666666",
      name: "Haiti",
      native: "Haïti",
      phonecode: "509",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 149,
      country_id: 32,
      capital: "Diego Garcia",
      currency_code: 32,
      domain: ".io",
      emoji: "????????",
      country_key: "IO",
      iso3: "IOT",
      latitude: "'-6",
      longitude: "71.5",
      name: "British Indian Ocean Territory",
      native: "British Indian Ocean Territory",
      phonecode: "246",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 150,
      country_id: 41,
      capital: "George Town",
      currency_code: 41,
      domain: ".ky",
      emoji: "????????",
      country_key: "KY",
      iso3: "CYM",
      latitude: "19.5",
      longitude: "'-80.5",
      name: "Cayman Islands",
      native: "Cayman Islands",
      phonecode: "'+1-345",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 151,
      country_id: 51,
      capital: "Kinshasa",
      currency_code: 51,
      domain: ".cd",
      emoji: "????????",
      country_key: "CD",
      iso3: "COD",
      latitude: "",
      longitude: "25",
      name: "Congo The Democratic Republic Of The",
      native: "République démocratique du Congo",
      phonecode: "243",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 152,
      country_id: 205,
      capital: "Grytviken",
      currency_code: 205,
      domain: ".gs",
      emoji: "????????",
      country_key: "GS",
      iso3: "SGS",
      latitude: "'-54.5",
      longitude: "'-37",
      name: "South Georgia",
      native: "South Georgia",
      phonecode: "",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 153,
      country_id: 238,
      capital: "Vatican City",
      currency_code: 238,
      domain: ".va",
      emoji: "????????",
      country_key: "VA",
      iso3: "VAT",
      latitude: "41.9",
      longitude: "12.45",
      name: "Vatican City State (Holy See)",
      native: "Vaticano",
      phonecode: "379",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 154,
      country_id: 100,
      capital: "Reykjavik",
      currency_code: 100,
      domain: ".is",
      emoji: "????????",
      country_key: "IS",
      iso3: "ISL",
      latitude: "65",
      longitude: "'-18",
      name: "Iceland",
      native: "Ísland",
      phonecode: "354",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 155,
      country_id: 214,
      capital: "Berne",
      currency_code: 214,
      domain: ".ch",
      emoji: "????????",
      country_key: "CH",
      iso3: "CHE",
      latitude: "47",
      longitude: "8",
      name: "Switzerland",
      native: "Schweiz",
      phonecode: "41",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 156,
      country_id: 78,
      capital: "Port-aux-Francais",
      currency_code: 78,
      domain: ".tf",
      emoji: "????????",
      country_key: "TF",
      iso3: "ATF",
      latitude: "'-49.25",
      longitude: "69.167",
      name: "French Southern Territories",
      native: "Territoire des Terres australes et antarctiques fr",
      phonecode: "",
      region: "Africa",
      subregion: "Southern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 157,
      country_id: 154,
      capital: "Kathmandu",
      currency_code: 154,
      domain: ".np",
      emoji: "????????",
      country_key: "NP",
      iso3: "NPL",
      latitude: "28",
      longitude: "84",
      name: "Nepal",
      native: "नपल",
      phonecode: "977",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 158,
      country_id: 219,
      capital: "Bangkok",
      currency_code: 219,
      domain: ".th",
      emoji: "????????",
      country_key: "TH",
      iso3: "THA",
      latitude: "15",
      longitude: "100",
      name: "Thailand",
      native: "ประเทศไทย",
      phonecode: "66",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 159,
      country_id: 176,
      capital: "Warsaw",
      currency_code: 176,
      domain: ".pl",
      emoji: "????????",
      country_key: "PL",
      iso3: "POL",
      latitude: "52",
      longitude: "20",
      name: "Poland",
      native: "Polska",
      phonecode: "48",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 160,
      country_id: 199,
      capital: "Singapur",
      currency_code: 199,
      domain: ".sg",
      emoji: "????????",
      country_key: "SG",
      iso3: "SGP",
      latitude: "1.36666666",
      longitude: "103.8",
      name: "Singapore",
      native: "Singapore",
      phonecode: "65",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 161,
      country_id: 83,
      capital: "Accra",
      currency_code: 83,
      domain: ".gh",
      emoji: "????????",
      country_key: "GH",
      iso3: "GHA",
      latitude: "8",
      longitude: "'-2",
      name: "Ghana",
      native: "Ghana",
      phonecode: "233",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 162,
      country_id: 68,
      capital: "Asmara",
      currency_code: 68,
      domain: ".er",
      emoji: "????????",
      country_key: "ER",
      iso3: "ERI",
      latitude: "15",
      longitude: "39",
      name: "Eritrea",
      native: "ኤርትራ",
      phonecode: "291",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 163,
      country_id: 188,
      capital: "Kingstown",
      currency_code: 188,
      domain: ".vc",
      emoji: "????????",
      country_key: "VC",
      iso3: "VCT",
      latitude: "13.25",
      longitude: "'-61.2",
      name: "Saint Vincent And The Grenadines",
      native: "Saint Vincent and the Grenadines",
      phonecode: "'+1-784",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 164,
      country_id: 65,
      capital: "Cairo",
      currency_code: 65,
      domain: ".eg",
      emoji: "????????",
      country_key: "EG",
      iso3: "EGY",
      latitude: "27",
      longitude: "30",
      name: "Egypt",
      native: "مصر‎",
      phonecode: "20",
      region: "Africa",
      subregion: "Northern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 165,
      country_id: 223,
      capital: "Port of Spain",
      currency_code: 223,
      domain: ".tt",
      emoji: "????????",
      country_key: "TT",
      iso3: "TTO",
      latitude: "11",
      longitude: "'-61",
      name: "Trinidad And Tobago",
      native: "Trinidad and Tobago",
      phonecode: "'+1-868",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 166,
      country_id: 34,
      capital: "Sofia",
      currency_code: 34,
      domain: ".bg",
      emoji: "????????",
      country_key: "BG",
      iso3: "BGR",
      latitude: "43",
      longitude: "25",
      name: "Bulgaria",
      native: "България",
      phonecode: "359",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 167,
      country_id: 101,
      capital: "New Delhi",
      currency_code: 101,
      domain: ".in",
      emoji: "????????",
      country_key: "IN",
      iso3: "IND",
      latitude: "20",
      longitude: "77",
      name: "India",
      native: "भारत",
      phonecode: "91",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 168,
      country_id: 23,
      capital: "Belmopan",
      currency_code: 23,
      domain: ".bz",
      emoji: "????????",
      country_key: "BZ",
      iso3: "BLZ",
      latitude: "17.25",
      longitude: "'-88.75",
      name: "Belize",
      native: "Belize",
      phonecode: "501",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 169,
      country_id: 157,
      capital: "Noumea",
      currency_code: 157,
      domain: ".nc",
      emoji: "????????",
      country_key: "NC",
      iso3: "NCL",
      latitude: "'-21.5",
      longitude: "165.5",
      name: "New Caledonia",
      native: "Nouvelle-Calédonie",
      phonecode: "687",
      region: "Oceania",
      subregion: "Melanesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 170,
      country_id: 213,
      capital: "Stockholm",
      currency_code: 213,
      domain: ".se",
      emoji: "????????",
      country_key: "SE",
      iso3: "SWE",
      latitude: "62",
      longitude: "15",
      name: "Sweden",
      native: "Sverige",
      phonecode: "46",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 171,
      country_id: 221,
      capital: "",
      currency_code: 221,
      domain: ".tk",
      emoji: "????????",
      country_key: "TK",
      iso3: "TKL",
      latitude: "'-9",
      longitude: "'-172",
      name: "Tokelau",
      native: "Tokelau",
      phonecode: "690",
      region: "Oceania",
      subregion: "Polynesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 172,
      country_id: 193,
      capital: "Sao Tome",
      currency_code: 193,
      domain: ".st",
      emoji: "????????",
      country_key: "ST",
      iso3: "STP",
      latitude: "1",
      longitude: "7",
      name: "Sao Tome and Principe",
      native: "São Tomé e Príncipe",
      phonecode: "239",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 173,
      country_id: 111,
      capital: "Amman",
      currency_code: 111,
      domain: ".jo",
      emoji: "????????",
      country_key: "JO",
      iso3: "JOR",
      latitude: "31",
      longitude: "36",
      name: "Jordan",
      native: "الأردن",
      phonecode: "962",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 174,
      country_id: 58,
      capital: "Prague",
      currency_code: 58,
      domain: ".cz",
      emoji: "????????",
      country_key: "CZ",
      iso3: "CZE",
      latitude: "49.75",
      longitude: "15.5",
      name: "Czech Republic",
      native: "Česká republika",
      phonecode: "420",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 175,
      country_id: 229,
      capital: "Kampala",
      currency_code: 229,
      domain: ".ug",
      emoji: "????????",
      country_key: "UG",
      iso3: "UGA",
      latitude: "1",
      longitude: "32",
      name: "Uganda",
      native: "Uganda",
      phonecode: "256",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 176,
      country_id: 209,
      capital: "Khartoum",
      currency_code: 209,
      domain: ".sd",
      emoji: "????????",
      country_key: "SD",
      iso3: "SDN",
      latitude: "15",
      longitude: "30",
      name: "Sudan",
      native: "السودان",
      phonecode: "249",
      region: "Africa",
      subregion: "Northern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 177,
      country_id: 182,
      capital: "Moscow",
      currency_code: 182,
      domain: ".ru",
      emoji: "????????",
      country_key: "RU",
      iso3: "RUS",
      latitude: "60",
      longitude: "100",
      name: "Russia",
      native: "Россия",
      phonecode: "7",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 178,
      country_id: 236,
      capital: "Tashkent",
      currency_code: 236,
      domain: ".uz",
      emoji: "????????",
      country_key: "UZ",
      iso3: "UZB",
      latitude: "41",
      longitude: "64",
      name: "Uzbekistan",
      native: "O‘zbekiston",
      phonecode: "998",
      region: "Asia",
      subregion: "Central Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 179,
      country_id: 159,
      capital: "Managua",
      currency_code: 159,
      domain: ".ni",
      emoji: "????????",
      country_key: "NI",
      iso3: "NIC",
      latitude: "13",
      longitude: "'-85",
      name: "Nicaragua",
      native: "Nicaragua",
      phonecode: "505",
      region: "Americas",
      subregion: "Central America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 180,
      country_id: 178,
      capital: "San Juan",
      currency_code: 178,
      domain: ".pr",
      emoji: "????????",
      country_key: "PR",
      iso3: "PRI",
      latitude: "18.25",
      longitude: "'-66.5",
      name: "Puerto Rico",
      native: "Puerto Rico",
      phonecode: "'+1-787 and 1-939",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 181,
      country_id: 46,
      capital: "Flying Fish Cove",
      currency_code: 46,
      domain: ".cx",
      emoji: "????????",
      country_key: "CX",
      iso3: "CXR",
      latitude: "'-10.5",
      longitude: "105.66666666",
      name: "Christmas Island",
      native: "Christmas Island",
      phonecode: "61",
      region: "Oceania",
      subregion: "Australia and New Zealand",
      status: "1",
      modifiedBy: null
  },
  {
      id: 182,
      country_id: 19,
      capital: "Dhaka",
      currency_code: 19,
      domain: ".bd",
      emoji: "????????",
      country_key: "BD",
      iso3: "BGD",
      latitude: "24",
      longitude: "90",
      name: "Bangladesh",
      native: "Bangladesh",
      phonecode: "880",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 183,
      country_id: 112,
      capital: "Astana",
      currency_code: 112,
      domain: ".kz",
      emoji: "????????",
      country_key: "KZ",
      iso3: "KAZ",
      latitude: "48",
      longitude: "68",
      name: "Kazakhstan",
      native: "Қазақстан",
      phonecode: "7",
      region: "Asia",
      subregion: "Central Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 184,
      country_id: 150,
      capital: "Maputo",
      currency_code: 150,
      domain: ".mz",
      emoji: "????????",
      country_key: "MZ",
      iso3: "MOZ",
      latitude: "'-18.25",
      longitude: "35",
      name: "Mozambique",
      native: "Moçambique",
      phonecode: "258",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 185,
      country_id: 210,
      capital: "Paramaribo",
      currency_code: 210,
      domain: ".sr",
      emoji: "????????",
      country_key: "SR",
      iso3: "SUR",
      latitude: "4",
      longitude: "'-56",
      name: "Suriname",
      native: "Suriname",
      phonecode: "597",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 186,
      country_id: 26,
      capital: "Thimphu",
      currency_code: 26,
      domain: ".bt",
      emoji: "????????",
      country_key: "BT",
      iso3: "BTN",
      latitude: "27.5",
      longitude: "90.5",
      name: "Bhutan",
      native: "ʼbrug-yul",
      phonecode: "975",
      region: "Asia",
      subregion: "Southern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 188,
      country_id: 158,
      capital: "Wellington",
      currency_code: 158,
      domain: ".nz",
      emoji: "????????",
      country_key: "NZ",
      iso3: "NZL",
      latitude: "'-41",
      longitude: "174",
      name: "New Zealand",
      native: "New Zealand",
      phonecode: "64",
      region: "Oceania",
      subregion: "Australia and New Zealand",
      status: "1",
      modifiedBy: null
  },
  {
      id: 189,
      country_id: 55,
      capital: "Zagreb",
      currency_code: 55,
      domain: ".hr",
      emoji: "????????",
      country_key: "HR",
      iso3: "HRV",
      latitude: "45.16666666",
      longitude: "15.5",
      name: "Croatia (Hrvatska)",
      native: "Hrvatska",
      phonecode: "385",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 190,
      country_id: 7,
      capital: "Luanda",
      currency_code: 7,
      domain: ".ao",
      emoji: "????????",
      country_key: "AO",
      iso3: "AGO",
      latitude: "'-12.5",
      longitude: "18.5",
      name: "Angola",
      native: "Angola",
      phonecode: "244",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 191,
      country_id: 184,
      capital: "Jamestown",
      currency_code: 184,
      domain: ".sh",
      emoji: "????????",
      country_key: "SH",
      iso3: "SHN",
      latitude: "'-15.95",
      longitude: "'-5.7",
      name: "Saint Helena",
      native: "Saint Helena",
      phonecode: "290",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 192,
      country_id: 211,
      capital: "Longyearbyen",
      currency_code: 211,
      domain: ".sj",
      emoji: "????????",
      country_key: "SJ",
      iso3: "SJM",
      latitude: "78",
      longitude: "20",
      name: "Svalbard And Jan Mayen Islands",
      native: "Svalbard og Jan Mayen",
      phonecode: "47",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 193,
      country_id: 56,
      capital: "Havana",
      currency_code: 56,
      domain: ".cu",
      emoji: "????????",
      country_key: "CU",
      iso3: "CUB",
      latitude: "21.5",
      longitude: "'-80",
      name: "Cuba",
      native: "Cuba",
      phonecode: "53",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 194,
      country_id: 203,
      capital: "Mogadishu",
      currency_code: 203,
      domain: ".so",
      emoji: "????????",
      country_key: "SO",
      iso3: "SOM",
      latitude: "10",
      longitude: "49",
      name: "Somalia",
      native: "Soomaaliya",
      phonecode: "252",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 195,
      country_id: 11,
      capital: "Buenos Aires",
      currency_code: 11,
      domain: ".ar",
      emoji: "????????",
      country_key: "AR",
      iso3: "ARG",
      latitude: "'-34",
      longitude: "'-64",
      name: "Argentina",
      native: "Argentina",
      phonecode: "54",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 196,
      country_id: 218,
      capital: "Dodoma",
      currency_code: 218,
      domain: ".tz",
      emoji: "????????",
      country_key: "TZ",
      iso3: "TZA",
      latitude: "'-6",
      longitude: "35",
      name: "Tanzania",
      native: "Tanzania",
      phonecode: "255",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 197,
      country_id: 3,
      capital: "Tirana",
      currency_code: 3,
      domain: ".al",
      emoji: "????????",
      country_key: "AL",
      iso3: "ALB",
      latitude: "41",
      longitude: "20",
      name: "Albania",
      native: "Shqipëria",
      phonecode: "355",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 198,
      country_id: 70,
      capital: "Addis Ababa",
      currency_code: 70,
      domain: ".et",
      emoji: "????????",
      country_key: "ET",
      iso3: "ETH",
      latitude: "8",
      longitude: "38",
      name: "Ethiopia",
      native: "ኢትዮጵያ",
      phonecode: "251",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 199,
      country_id: 190,
      capital: "Marigot",
      currency_code: 190,
      domain: ".mf",
      emoji: "????????",
      country_key: "MF",
      iso3: "MAF",
      latitude: "18.08333333",
      longitude: "'-63.95",
      name: "Saint-Martin (French part)",
      native: "Saint-Martin",
      phonecode: "590",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 200,
      country_id: 85,
      capital: "Athens",
      currency_code: 85,
      domain: ".gr",
      emoji: "????????",
      country_key: "GR",
      iso3: "GRC",
      latitude: "39",
      longitude: "22",
      name: "Greece",
      native: "Ελλάδα",
      phonecode: "30",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 201,
      country_id: 69,
      capital: "Tallinn",
      currency_code: 69,
      domain: ".ee",
      emoji: "????????",
      country_key: "EE",
      iso3: "EST",
      latitude: "59",
      longitude: "26",
      name: "Estonia",
      native: "Eesti",
      phonecode: "372",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 202,
      country_id: 164,
      capital: "Saipan",
      currency_code: 164,
      domain: ".mp",
      emoji: "????????",
      country_key: "MP",
      iso3: "MNP",
      latitude: "15.2",
      longitude: "145.75",
      name: "Northern Mariana Islands",
      native: "Northern Mariana Islands",
      phonecode: "'+1-670",
      region: "Oceania",
      subregion: "Micronesia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 203,
      country_id: 20,
      capital: "Bridgetown",
      currency_code: 20,
      domain: ".bb",
      emoji: "????????",
      country_key: "BB",
      iso3: "BRB",
      latitude: "13.16666666",
      longitude: "'-59.53333333",
      name: "Barbados",
      native: "Barbados",
      phonecode: "'+1-246",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 204,
      country_id: 39,
      capital: "Ottawa",
      currency_code: 39,
      domain: ".ca",
      emoji: "????????",
      country_key: "CA",
      iso3: "CAN",
      latitude: "60",
      longitude: "'-95",
      name: "Canada",
      native: "Canada",
      phonecode: "1",
      region: "Americas",
      subregion: "Northern America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 205,
      country_id: 45,
      capital: "Beijing",
      currency_code: 45,
      domain: ".cn",
      emoji: "????????",
      country_key: "CN",
      iso3: "CHN",
      latitude: "35",
      longitude: "105",
      name: "China",
      native: "中国",
      phonecode: "86",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 206,
      country_id: 123,
      capital: "Monrovia",
      currency_code: 123,
      domain: ".lr",
      emoji: "????????",
      country_key: "LR",
      iso3: "LBR",
      latitude: "6.5",
      longitude: "'-9.5",
      name: "Liberia",
      native: "Liberia",
      phonecode: "231",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 207,
      country_id: 124,
      capital: "Tripolis",
      currency_code: 124,
      domain: ".ly",
      emoji: "????????",
      country_key: "LY",
      iso3: "LBY",
      latitude: "25",
      longitude: "17",
      name: "Libya",
      native: "‏ليبيا",
      phonecode: "218",
      region: "Africa",
      subregion: "Northern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 208,
      country_id: 161,
      capital: "Abuja",
      currency_code: 161,
      domain: ".ng",
      emoji: "????????",
      country_key: "NG",
      iso3: "NGA",
      latitude: "10",
      longitude: "8",
      name: "Nigeria",
      native: "Nigeria",
      phonecode: "234",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 209,
      country_id: 181,
      capital: "Bucharest",
      currency_code: 181,
      domain: ".ro",
      emoji: "????????",
      country_key: "RO",
      iso3: "ROU",
      latitude: "46",
      longitude: "25",
      name: "Romania",
      native: "România",
      phonecode: "40",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 210,
      country_id: 74,
      capital: "Helsinki",
      currency_code: 74,
      domain: ".fi",
      emoji: "????????",
      country_key: "FI",
      iso3: "FIN",
      latitude: "64",
      longitude: "26",
      name: "Finland",
      native: "Suomi",
      phonecode: "358",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 211,
      country_id: 37,
      capital: "Phnom Penh",
      currency_code: 37,
      domain: ".kh",
      emoji: "????????",
      country_key: "KH",
      iso3: "KHM",
      latitude: "13",
      longitude: "105",
      name: "Cambodia",
      native: "Kâmpŭchéa",
      phonecode: "855",
      region: "Asia",
      subregion: "South-Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 212,
      country_id: 93,
      capital: "Bissau",
      currency_code: 93,
      domain: ".gw",
      emoji: "????????",
      country_key: "GW",
      iso3: "GNB",
      latitude: "12",
      longitude: "'-15",
      name: "Guinea-Bissau",
      native: "Guiné-Bissau",
      phonecode: "245",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 213,
      country_id: 160,
      capital: "Niamey",
      currency_code: 160,
      domain: ".ne",
      emoji: "????????",
      country_key: "NE",
      iso3: "NER",
      latitude: "16",
      longitude: "8",
      name: "Niger",
      native: "Niger",
      phonecode: "227",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 214,
      country_id: 29,
      capital: "Gaborone",
      currency_code: 29,
      domain: ".bw",
      emoji: "????????",
      country_key: "BW",
      iso3: "BWA",
      latitude: "'-22",
      longitude: "24",
      name: "Botswana",
      native: "Botswana",
      phonecode: "267",
      region: "Africa",
      subregion: "Southern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 215,
      country_id: 86,
      capital: "Nuuk",
      currency_code: 86,
      domain: ".gl",
      emoji: "????????",
      country_key: "GL",
      iso3: "GRL",
      latitude: "72",
      longitude: "'-40",
      name: "Greenland",
      native: "Kalaallit Nunaat",
      phonecode: "299",
      region: "Americas",
      subregion: "Northern America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 216,
      country_id: 21,
      capital: "Minsk",
      currency_code: 21,
      domain: ".by",
      emoji: "????????",
      country_key: "BY",
      iso3: "BLR",
      latitude: "53",
      longitude: "28",
      name: "Belarus",
      native: "Белару́сь",
      phonecode: "375",
      region: "Europe",
      subregion: "Eastern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 217,
      country_id: 25,
      capital: "Hamilton",
      currency_code: 25,
      domain: ".bm",
      emoji: "????????",
      country_key: "BM",
      iso3: "BMU",
      latitude: "32.33333333",
      longitude: "'-64.75",
      name: "Bermuda",
      native: "Bermuda",
      phonecode: "'+1-441",
      region: "Americas",
      subregion: "Northern America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 218,
      country_id: 134,
      capital: "Bamako",
      currency_code: 134,
      domain: ".ml",
      emoji: "????????",
      country_key: "ML",
      iso3: "MLI",
      latitude: "17",
      longitude: "'-4",
      name: "Mali",
      native: "Mali",
      phonecode: "223",
      region: "Africa",
      subregion: "Western Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 219,
      country_id: 177,
      capital: "Lisbon",
      currency_code: 177,
      domain: ".pt",
      emoji: "????????",
      country_key: "PT",
      iso3: "PRT",
      latitude: "39.5",
      longitude: "'-8",
      name: "Portugal",
      native: "Portugal",
      phonecode: "351",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 220,
      country_id: 125,
      capital: "Vaduz",
      currency_code: 125,
      domain: ".li",
      emoji: "????????",
      country_key: "LI",
      iso3: "LIE",
      latitude: "47.26666666",
      longitude: "9.53333333",
      name: "Liechtenstein",
      native: "Liechtenstein",
      phonecode: "423",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 221,
      country_id: 185,
      capital: "Basseterre",
      currency_code: 185,
      domain: ".kn",
      emoji: "????????",
      country_key: "KN",
      iso3: "KNA",
      latitude: "17.33333333",
      longitude: "'-62.75",
      name: "Saint Kitts And Nevis",
      native: "Saint Kitts and Nevis",
      phonecode: "'+1-869",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 222,
      country_id: 235,
      capital: "Montevideo",
      currency_code: 235,
      domain: ".uy",
      emoji: "????????",
      country_key: "UY",
      iso3: "URY",
      latitude: "'-33",
      longitude: "'-56",
      name: "Uruguay",
      native: "Uruguay",
      phonecode: "598",
      region: "Americas",
      subregion: "South America",
      status: "1",
      modifiedBy: null
  },
  {
      id: 223,
      country_id: 12,
      capital: "Yerevan",
      currency_code: 12,
      domain: ".am",
      emoji: "????????",
      country_key: "AM",
      iso3: "ARM",
      latitude: "40",
      longitude: "45",
      name: "Armenia",
      native: "Հայաստան",
      phonecode: "374",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 224,
      country_id: 17,
      capital: "Nassau",
      currency_code: 17,
      domain: ".bs",
      emoji: "????????",
      country_key: "BS",
      iso3: "BHS",
      latitude: "24.25",
      longitude: "'-76",
      name: "Bahamas The",
      native: "Bahamas",
      phonecode: "'+1-242",
      region: "Americas",
      subregion: "Caribbean",
      status: "1",
      modifiedBy: null
  },
  {
      id: 227,
      country_id: 226,
      capital: "Ashgabat",
      currency_code: 226,
      domain: ".tm",
      emoji: "????????",
      country_key: "TM",
      iso3: "TKM",
      latitude: "40",
      longitude: "60",
      name: "Turkmenistan",
      native: "Türkmenistan",
      phonecode: "993",
      region: "Asia",
      subregion: "Central Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 228,
      country_id: 57,
      capital: "Nicosia",
      currency_code: 57,
      domain: ".cy",
      emoji: "????????",
      country_key: "CY",
      iso3: "CYP",
      latitude: "35",
      longitude: "33",
      name: "Cyprus",
      native: "Κύπρος",
      phonecode: "357",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 229,
      country_id: 47,
      capital: "West Island",
      currency_code: 47,
      domain: ".cc",
      emoji: "????????",
      country_key: "CC",
      iso3: "CCK",
      latitude: "'-12.5",
      longitude: "96.83333333",
      name: "Cocos (Keeling) Islands",
      native: "Cocos (Keeling) Islands",
      phonecode: "61",
      region: "Oceania",
      subregion: "Australia and New Zealand",
      status: "1",
      modifiedBy: null
  },
  {
      id: 230,
      country_id: 196,
      capital: "Belgrade",
      currency_code: 196,
      domain: ".rs",
      emoji: "????????",
      country_key: "RS",
      iso3: "SRB",
      latitude: "44",
      longitude: "21",
      name: "Serbia",
      native: "Србија",
      phonecode: "381",
      region: "Europe",
      subregion: "Southern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 231,
      country_id: 197,
      capital: "Victoria",
      currency_code: 197,
      domain: ".sc",
      emoji: "????????",
      country_key: "SC",
      iso3: "SYC",
      latitude: "'-4.58333333",
      longitude: "55.66666666",
      name: "Seychelles",
      native: "Seychelles",
      phonecode: "248",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 232,
      country_id: 215,
      capital: "Damascus",
      currency_code: 215,
      domain: ".sy",
      emoji: "????????",
      country_key: "SY",
      iso3: "SYR",
      latitude: "35",
      longitude: "38",
      name: "Syria",
      native: "سوريا",
      phonecode: "963",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 233,
      country_id: 15,
      capital: "Vienna",
      currency_code: 15,
      domain: ".at",
      emoji: "????????",
      country_key: "AT",
      iso3: "AUT",
      latitude: "47.33333333",
      longitude: "13.33333333",
      name: "Austria",
      native: "Österreich",
      phonecode: "43",
      region: "Europe",
      subregion: "Western Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 234,
      country_id: 149,
      capital: "Rabat",
      currency_code: 149,
      domain: ".ma",
      emoji: "????????",
      country_key: "MA",
      iso3: "MAR",
      latitude: "32",
      longitude: "'-5",
      name: "Morocco",
      native: "المغرب",
      phonecode: "212",
      region: "Africa",
      subregion: "Northern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 235,
      country_id: 216,
      capital: "Taipei",
      currency_code: 216,
      domain: ".tw",
      emoji: "????????",
      country_key: "TW",
      iso3: "TWN",
      latitude: "23.5",
      longitude: "121",
      name: "Taiwan",
      native: "臺灣",
      phonecode: "886",
      region: "Asia",
      subregion: "Eastern Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 236,
      country_id: 166,
      capital: "Muscat",
      currency_code: 166,
      domain: ".om",
      emoji: "????????",
      country_key: "OM",
      iso3: "OMN",
      latitude: "21",
      longitude: "57",
      name: "Oman",
      native: "عمان",
      phonecode: "968",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 237,
      country_id: 42,
      capital: "Bangui",
      currency_code: 42,
      domain: ".cf",
      emoji: "????????",
      country_key: "CF",
      iso3: "CAF",
      latitude: "7",
      longitude: "21",
      name: "Central African Republic",
      native: "Ködörösêse tî Bêafrîka",
      phonecode: "236",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 238,
      country_id: 183,
      capital: "Kigali",
      currency_code: 183,
      domain: ".rw",
      emoji: "????????",
      country_key: "RW",
      iso3: "RWA",
      latitude: "'-2",
      longitude: "30",
      name: "Rwanda",
      native: "Rwanda",
      phonecode: "250",
      region: "Africa",
      subregion: "Eastern Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 239,
      country_id: 43,
      capital: "N'Djamena",
      currency_code: 43,
      domain: ".td",
      emoji: "????????",
      country_key: "TD",
      iso3: "TCD",
      latitude: "15",
      longitude: "19",
      name: "Chad",
      native: "Tchad",
      phonecode: "235",
      region: "Africa",
      subregion: "Middle Africa",
      status: "1",
      modifiedBy: null
  },
  {
      id: 240,
      country_id: 14,
      capital: "Canberra",
      currency_code: 14,
      domain: ".au",
      emoji: "????????",
      country_key: "AU",
      iso3: "AUS",
      latitude: "'-27",
      longitude: "133",
      name: "Australia",
      native: "Australia",
      phonecode: "61",
      region: "Oceania",
      subregion: "Australia and New Zealand",
      status: "1",
      modifiedBy: null
  },
  {
      id: 241,
      country_id: 72,
      capital: "Torshavn",
      currency_code: 72,
      domain: ".fo",
      emoji: "????????",
      country_key: "FO",
      iso3: "FRO",
      latitude: "62",
      longitude: "'-7",
      name: "Faroe Islands",
      native: "Føroyar",
      phonecode: "298",
      region: "Europe",
      subregion: "Northern Europe",
      status: "1",
      modifiedBy: null
  },
  {
      id: 242,
      country_id: 225,
      capital: "Ankara",
      currency_code: 225,
      domain: ".tr",
      emoji: "????????",
      country_key: "TR",
      iso3: "TUR",
      latitude: "39",
      longitude: "35",
      name: "Turkey",
      native: "Türkiye",
      phonecode: "90",
      region: "Asia",
      subregion: "Western Asia",
      status: "1",
      modifiedBy: null
  },
  {
      id: 243,
      country_id: 122,
      capital: "Maseru",
      currency_code: 122,
      domain: ".ls",
      emoji: "????????",
      country_key: "LS",
      iso3: "LSO",
      latitude: "29.5",
      longitude: "28.5",
      name: "Lesotho",
      native: "Lesotho",
      phonecode: "266",
      region: "Africa",
      subregion: "Southern Africa",
      status: "1",
      modifiedBy: null
  }
  ]);
}
