/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex('fields_config').del()
  await knex('fields_config').insert([
    {
      id: 1,
      subscriber_id: "1",
      key: "emailID",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "Email ID",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 2,
      subscriber_id: "1",
      key: "mobile",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Mobile Phone",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 3,
      subscriber_id: "1",
      key: "telephone",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Telephone",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 4,
      subscriber_id: "1",
      key: "designation",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Designation",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 5,
      subscriber_id: "1",
      key: "contactPersonName",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Contact Person Name",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 6,
      subscriber_id: "1",
      key: "cinNo",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "CIN Number",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 7,
      subscriber_id: "1",
      key: "aadharNo",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Aadhar Card Number",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 8,
      subscriber_id: "1",
      key: "officeDetails",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Office Details",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 9,
      subscriber_id: "1",
      key: "paymentMethod",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "Payment Method",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 10,
      subscriber_id: "1",
      key: "website",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Website",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 11,
      subscriber_id: "1",
      key: "phoneNo",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Phone Number",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 12,
      subscriber_id: "1",
      key: "pin",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "Pincode",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 13,
      subscriber_id: "1",
      key: "city",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "City",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 14,
      subscriber_id: "1",
      key: "country",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "Country",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 15,
      subscriber_id: "1",
      key: "address3",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "Address 3rd",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 16,
      subscriber_id: "1",
      key: "address2",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Address 2nd",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 17,
      subscriber_id: "1",
      key: "address1",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Address 1st",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 18,
      subscriber_id: "1",
      key: "streetNo",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Street Number",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 19,
      subscriber_id: "1",
      key: "source",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Source",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 20,
      subscriber_id: "1",
      key: "supplier_name",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Supplier Name",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 21,
      subscriber_id: "1",
      key: "add",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Address",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 22,
      subscriber_id: "1",
      key: "state",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "State",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 23,
      subscriber_id: "1",
      key: "detailsOfMajorLastYear",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Details of Major Last Year",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 24,
      subscriber_id: "1",
      key: "listOfMajorCustomers",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "List of Major Customers",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 25,
      subscriber_id: "1",
      key: "nameOfOtherGroupCompanies",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Name of Other Group Companies",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 26,
      subscriber_id: "1",
      key: "addressOfPlant",
      field_type: "Textarea",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Address of Plant",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 27,
      subscriber_id: "1",
      key: "businessType",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Business Type",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 28,
      subscriber_id: "1",
      key: "nameOfBusiness",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Name of Business",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 29,
      subscriber_id: "1",
      key: "companyType",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Company Type",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 30,
      subscriber_id: "1",
      key: "promoterName",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Promoter Name",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 31,
      subscriber_id: "1",
      key: "companyFoundYear",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "Company Found Year",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 32,
      subscriber_id: "1",
      key: "currency",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "1",
      display_name: "Currency",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 33,
      subscriber_id: "1",
      key: "Turnover",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Turnover",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 34,
      subscriber_id: "1",
      key: "Turnover2",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Turnover 2nd",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 35,
      subscriber_id: "1",
      key: "Turnover3",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Turnover 3rd",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 36,
      subscriber_id: "1",
      key: "first",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "First",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 37,
      subscriber_id: "1",
      key: "second",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Second",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 38,
      subscriber_id: "1",
      key: "third",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Third",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 39,
      subscriber_id: "1",
      key: "afterfirst",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "After First",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 40,
      subscriber_id: "1",
      key: "aftersecond",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "After Second",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 41,
      subscriber_id: "1",
      key: "afterthird",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "After Third",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 42,
      subscriber_id: "1",
      key: "presentorder",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Present Order",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 43,
      subscriber_id: "1",
      key: "furtherorder",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Further Order",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 44,
      subscriber_id: "1",
      key: "market",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Market",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 45,
      subscriber_id: "1",
      key: "networth",
      field_type: "Number",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Networth",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 46,
      subscriber_id: "1",
      key: "gstNo",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "0",
      display_name: "GST Number",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 47,
      subscriber_id: "1",
      key: "gstRegDate",
      field_type: "Date",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "0",
      display_name: "GST Registration Date",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 48,
      subscriber_id: "1",
      key: "msmeImage",
      field_type: "File",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "0",
      display_name: "MSME Image",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 49,
      subscriber_id: "1",
      key: "gstImage",
      field_type: "File",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "0",
      display_name: "GST Image",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 50,
      subscriber_id: "1",
      key: "cancelledChequeImage",
      field_type: "File",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "1",
      display_name: "Cancelled Cheque Image",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 51,
      subscriber_id: "1",
      key: "panCardImage",
      field_type: "File",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "1",
      display_name: "Pancard Image",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 78,
      subscriber_id: "1",
      key: "gst_no",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "GST Number",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 79,
      subscriber_id: "1",
      key: "panNo",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "0",
      display_name: "Pan Number",
      panel_id: 1,
      display: "1",
      is_primary: "1",
      modifiedBy: null
  },
  {
      id: 136,
      subscriber_id: "1",
      key: "department",
      field_type: "TextField",
      module_name: "supplier_registration",
      group_name: "companyDetails",
      required: "1",
      display_name: "Department",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 137,
      subscriber_id: "1",
      key: "p_bank_name",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank Name",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 138,
      subscriber_id: "1",
      key: "p_bank_account_number",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "1",
      display_name: "Primary Bank Account Number",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 139,
      subscriber_id: "1",
      key: "p_bank_account_holder_name",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank Account Holder Name",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 140,
      subscriber_id: "1",
      key: "p_bank_state",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank State",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 141,
      subscriber_id: "1",
      key: "p_bank_address",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank Address",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 142,
      subscriber_id: "1",
      key: "p_bank_branch",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank Branch",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 143,
      subscriber_id: "1",
      key: "p_ifsc_code",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "1",
      display_name: "Primary Bank IFSC Code",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 144,
      subscriber_id: "1",
      key: "p_micr_code",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank MICR Code",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 145,
      subscriber_id: "1",
      key: "p_bank_guarantee_limit",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank Guarantee Limit",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 146,
      subscriber_id: "1",
      key: "p_overdraft_cash_credit_limit",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Primary Bank OverDraft/Cash Credit Limit",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 147,
      subscriber_id: "1",
      key: "s_bank_name",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank Name",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 148,
      subscriber_id: "1",
      key: "s_bank_account_number",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank Account Number",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 149,
      subscriber_id: "1",
      key: "s_bank_account_holder_name",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank Account Holder Name",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 150,
      subscriber_id: "1",
      key: "s_bank_state",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank State",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 151,
      subscriber_id: "1",
      key: "s_bank_address",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank Address",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 152,
      subscriber_id: "1",
      key: "s_bank_branch",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank Branch",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 153,
      subscriber_id: "1",
      key: "s_ifsc_code",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank IFSC Code",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 154,
      subscriber_id: "1",
      key: "s_micr_code",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank MICR Code",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 155,
      subscriber_id: "1",
      key: "s_bank_guarantee_limit",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank Guarantee Limit",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 156,
      subscriber_id: "1",
      key: "s_overdraft_cash_credit_limit",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "financialDetails",
      required: "0",
      display_name: "Secondary Bank OverDraft/Cash Credit Limit",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 157,
      subscriber_id: "1",
      key: "msme_no",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "MSME Number",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 158,
      subscriber_id: "1",
      key: "msmeType",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "businessDetails",
      required: "0",
      display_name: "MSME Type",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 159,
      subscriber_id: "1",
      key: "otherAttachments",
      field_type: "Text",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "0",
      display_name: "Other Attachments",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  },
  {
      id: 162,
      subscriber_id: "1",
      key: "pfAttachment",
      field_type: "File",
      module_name: "supplier_registration",
      group_name: "taxDetails",
      required: "0",
      display_name: "PF Attachments",
      panel_id: 1,
      display: "1",
      is_primary: "0",
      modifiedBy: null
  }
  ]);
}
