/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed (knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex("gst_states").del();
  await knex("gst_states").insert([
    {
      id: 1,
      name: "Jammu and Kashmir",
      code: "01",
      modifiedBy: null,
    },
    {
      id: 2,
      name: "Himachal Pradesh",
      code: "02",
      modifiedBy: null,
    },
    {
      id: 3,
      name: "Punjab",
      code: "03",
      modifiedBy: null,
    },
    {
      id: 4,
      name: "Chandigarh",
      code: "04",
      modifiedBy: null,
    },
    {
      id: 5,
      name: "Uttarakhand",
      code: "05",
      modifiedBy: null,
    },
    {
      id: 6,
      name: "Haryana",
      code: "06",
      modifiedBy: null,
    },
    {
      id: 7,
      name: "Delhi",
      code: "07",
      modifiedBy: null,
    },
    {
      id: 8,
      name: "Rajasthan",
      code: "08",
      modifiedBy: null,
    },
    {
      id: 9,
      name: "Uttar Pradesh",
      code: "09",
      modifiedBy: null,
    },
    {
      id: 10,
      name: "Bihar",
      code: "10",
      modifiedBy: null,
    },
    {
      id: 11,
      name: "Sikkim",
      code: "11",
      modifiedBy: null,
    },
    {
      id: 12,
      name: "Arunachal Pradesh",
      code: "12",
      modifiedBy: null,
    },
    {
      id: 13,
      name: "Nagaland",
      code: "13",
      modifiedBy: null,
    },
    {
      id: 14,
      name: "Manipur",
      code: "14",
      modifiedBy: null,
    },
    {
      id: 15,
      name: "Mizoram",
      code: "15",
      modifiedBy: null,
    },
    {
      id: 16,
      name: "Tripura",
      code: "16",
      modifiedBy: null,
    },
    {
      id: 17,
      name: "Meghalaya",
      code: "17",
      modifiedBy: null,
    },
    {
      id: 18,
      name: "Assam",
      code: "18",
      modifiedBy: null,
    },
    {
      id: 19,
      name: "West Bengal",
      code: "19",
      modifiedBy: null,
    },
    {
      id: 20,
      name: "Jharkhand",
      code: "20",
      modifiedBy: null,
    },
    {
      id: 21,
      name: "Odisha",
      code: "21",
      modifiedBy: null,
    },
    {
      id: 22,
      name: "Chattisgarh",
      code: "22",
      modifiedBy: null,
    },
    {
      id: 23,
      name: "Madhya Pradesh",
      code: "23",
      modifiedBy: null,
    },
    {
      id: 24,
      name: "Gujarat",
      code: "24",
      modifiedBy: null,
    },
    {
      id: 25,
      name: "Daman and Diu",
      code: "25",
      modifiedBy: null,
    },
    {
      id: 26,
      name: "Dadra and Nagar Haveli",
      code: "26",
      modifiedBy: null,
    },
    {
      id: 27,
      name: "Maharashtra",
      code: "27",
      modifiedBy: null,
    },
    {
      id: 28,
      name: "Andhra Pradesh",
      code: "28",
      modifiedBy: null,
    },
    {
      id: 29,
      name: "Karnataka",
      code: "29",
      modifiedBy: null,
    },
    {
      id: 30,
      name: "Goa",
      code: "30",
      modifiedBy: null,
    },
    {
      id: 31,
      name: "Lakshadweep Islands",
      code: "31",
      modifiedBy: null,
    },
    {
      id: 32,
      name: "Kerala",
      code: "32",
      modifiedBy: null,
    },
    {
      id: 33,
      name: "Tamil Nadu",
      code: "33",
      modifiedBy: null,
    },
    {
      id: 34,
      name: "Pondicherry",
      code: "34",
      modifiedBy: null,
    },
    {
      id: 35,
      name: "Andaman and Nicobar Islands",
      code: "35",
      modifiedBy: null,
    },
    {
      id: 36,
      name: "Telangana",
      code: "36",
      modifiedBy: null,
    },
    {
      id: 37,
      name: "Andhra Pradesh (new)",
      code: "37",
      modifiedBy: null,
    },
    {
      id: 38,
      name: "Ladakh",
      code: "38",
      modifiedBy: null,
    },
    {
      id: 39,
      name: "Jammu and Kashmir",
      code: "01",
      modifiedBy: null,
    },
    {
      id: 40,
      name: "Himachal Pradesh",
      code: "02",
      modifiedBy: null,
    },
    {
      id: 41,
      name: "Punjab",
      code: "03",
      modifiedBy: null,
    },
    {
      id: 42,
      name: "Chandigarh",
      code: "04",
      modifiedBy: null,
    },
    {
      id: 43,
      name: "Uttarakhand",
      code: "05",
      modifiedBy: null,
    },
    {
      id: 44,
      name: "Haryana",
      code: "06",
      modifiedBy: null,
    },
    {
      id: 45,
      name: "Delhi",
      code: "07",
      modifiedBy: null,
    },
    {
      id: 46,
      name: "Rajasthan",
      code: "08",
      modifiedBy: null,
    },
    {
      id: 47,
      name: "Uttar Pradesh",
      code: "09",
      modifiedBy: null,
    },
    {
      id: 48,
      name: "Bihar",
      code: "10",
      modifiedBy: null,
    },
    {
      id: 49,
      name: "Sikkim",
      code: "11",
      modifiedBy: null,
    },
    {
      id: 50,
      name: "Arunachal Pradesh",
      code: "12",
      modifiedBy: null,
    },
    {
      id: 51,
      name: "Nagaland",
      code: "13",
      modifiedBy: null,
    },
    {
      id: 52,
      name: "Manipur",
      code: "14",
      modifiedBy: null,
    },
    {
      id: 53,
      name: "Mizoram",
      code: "15",
      modifiedBy: null,
    },
    {
      id: 54,
      name: "Tripura",
      code: "16",
      modifiedBy: null,
    },
    {
      id: 55,
      name: "Meghalaya",
      code: "17",
      modifiedBy: null,
    },
    {
      id: 56,
      name: "Assam",
      code: "18",
      modifiedBy: null,
    },
    {
      id: 57,
      name: "West Bengal",
      code: "19",
      modifiedBy: null,
    },
    {
      id: 58,
      name: "Jharkhand",
      code: "20",
      modifiedBy: null,
    },
    {
      id: 59,
      name: "Odisha",
      code: "21",
      modifiedBy: null,
    },
    {
      id: 60,
      name: "Chattisgarh",
      code: "22",
      modifiedBy: null,
    },
    {
      id: 61,
      name: "Madhya Pradesh",
      code: "23",
      modifiedBy: null,
    },
    {
      id: 62,
      name: "Gujarat",
      code: "24",
      modifiedBy: null,
    },
    {
      id: 63,
      name: "Daman and Diu",
      code: "25",
      modifiedBy: null,
    },
    {
      id: 64,
      name: "Dadra and Nagar Haveli",
      code: "26",
      modifiedBy: null,
    },
    {
      id: 65,
      name: "Maharashtra",
      code: "27",
      modifiedBy: null,
    },
    {
      id: 66,
      name: "Andhra Pradesh",
      code: "28",
      modifiedBy: null,
    },
    {
      id: 67,
      name: "Karnataka",
      code: "29",
      modifiedBy: null,
    },
    {
      id: 68,
      name: "Goa",
      code: "30",
      modifiedBy: null,
    },
    {
      id: 69,
      name: "Lakshadweep Islands",
      code: "31",
      modifiedBy: null,
    },
    {
      id: 70,
      name: "Kerala",
      code: "32",
      modifiedBy: null,
    },
    {
      id: 71,
      name: "Tamil Nadu",
      code: "33",
      modifiedBy: null,
    },
    {
      id: 72,
      name: "Pondicherry",
      code: "34",
      modifiedBy: null,
    },
    {
      id: 73,
      name: "Andaman and Nicobar Islands",
      code: "35",
      modifiedBy: null,
    },
    {
      id: 74,
      name: "Telangana",
      code: "36",
      modifiedBy: null,
    },
    {
      id: 75,
      name: "Andhra Pradesh (new)",
      code: "37",
      modifiedBy: null,
    },
    {
      id: 76,
      name: "Ladakh",
      code: "38",
      modifiedBy: null,
    },
  ]);
}
