/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed (knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex("payment_terms").del();
  await knex("payment_terms").insert([
    {
      id: 1,
      code: " ",
      name: "Select",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 12,
      code: "Z005",
      name: "5 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 13,
      code: "Z007",
      name: "7 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 14,
      code: "Z00A",
      name: "Advance",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 15,
      code: "Z010",
      name: "10 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 16,
      code: "Z013",
      name: "13 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 17,
      code: "Z015",
      name: "15 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 18,
      code: "Z020",
      name: "20 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 19,
      code: "Z025",
      name: "25 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 20,
      code: "Z030",
      name: "30 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 21,
      code: "Z035",
      name: "35 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 22,
      code: "Z040",
      name: "40 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 23,
      code: "Z045",
      name: "45 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 24,
      code: "Z050",
      name: "50 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 25,
      code: "Z055",
      name: "55 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 26,
      code: "Z060",
      name: "60 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 27,
      code: "Z065",
      name: "65 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 28,
      code: "Z070",
      name: "70 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 29,
      code: "Z075",
      name: "75 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 30,
      code: "Z080",
      name: "80 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 31,
      code: "Z085",
      name: "85 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 32,
      code: "Z090",
      name: "90 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 33,
      code: "Z095",
      name: "95 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 34,
      code: "Z100",
      name: "100 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 35,
      code: "Z105",
      name: "105 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 36,
      code: "Z110",
      name: "110 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 37,
      code: "Z115",
      name: "115 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 38,
      code: "Z120",
      name: "120 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 39,
      code: "Z125",
      name: "125 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 40,
      code: "Z130",
      name: "130 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 41,
      code: "Z135",
      name: "135 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 42,
      code: "Z140",
      name: "140 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 43,
      code: "Z145",
      name: "145 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 44,
      code: "Z150",
      name: "150 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 45,
      code: "Z155",
      name: "155 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 46,
      code: "Z160",
      name: "160 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 47,
      code: "Z165",
      name: "165 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 48,
      code: "Z170",
      name: "170 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 49,
      code: "Z175",
      name: "175 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 50,
      code: "Z180",
      name: "180 days",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 51,
      code: "Z300",
      name: "Loan Installemnts",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 52,
      code: "Z301",
      name: "1 year",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 53,
      code: "Z302",
      name: "1.5 years",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 54,
      code: "Z303",
      name: "2 years",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 55,
      code: "0001",
      name: "Payable immediately Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 56,
      code: "0002",
      name: "within 14 days 2 % cash discount  within 30 days D",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 57,
      code: "0003",
      name: "within 14 days 3 % cash discount within 20 days 2 ",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 58,
      code: "0004",
      name: "Payable immediately Due net Baseline date on End o",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 59,
      code: "0005",
      name: "Payable immediately Due net  Baseline date on 10 o",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 60,
      code: "0006",
      name: "Before End of the month 4 % cash discount Before 1",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 61,
      code: "0007",
      name: "For incoming invoices until 15 of the month Before",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 62,
      code: "0009",
      name: "Payable in 3 partial amounts, 1 installment: 30.00",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 63,
      code: "0008",
      name: "For incoming invoices until 15 of the month within",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 69,
      code: "0002",
      name: "within 14 days 2 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 70,
      code: "",
      name: "within 30 days Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 71,
      code: "0003",
      name: "within 14 days 3 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 72,
      code: "",
      name: "within 20 days 2 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 73,
      code: "",
      name: "within 30 days Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 74,
      code: "0004",
      name: "Payable immediately Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 75,
      code: "",
      name: "Baseline date on End of the month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 76,
      code: "0005",
      name: "Payable immediately Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 77,
      code: "",
      name: "Baseline date on 10 of next month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 78,
      code: "0006",
      name: "Before End of the month 4 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 79,
      code: "",
      name: "Before 15 of the next month ;; 2 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 80,
      code: "",
      name: "Before 15 in 2 months Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 81,
      code: "0007",
      name: "For incoming invoices until 15 of the month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 82,
      code: "",
      name: "Before 15 of the next month ;; 2 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 83,
      code: "",
      name: "Before End of the next month ;; Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 84,
      code: "",
      name: "For incoming invoices until End  of the month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 85,
      code: "",
      name: "Before End of the next month ;; 2 % cash discoun",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 86,
      code: "",
      name: "Before 15 in 2 months Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 87,
      code: "0008",
      name: "For incoming invoices until 15 of the month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 88,
      code: "",
      name: "within 14 days 2 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 89,
      code: "",
      name: "within 30 days 1.5 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 90,
      code: "",
      name: "within 45 days Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 91,
      code: "",
      name: "Baseline date on 30 of the month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 92,
      code: "",
      name: "For incoming invoices until End  of the month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 93,
      code: "",
      name: "within 14 days 2 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 94,
      code: "",
      name: "within 30 days 1.5 % cash discount",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 95,
      code: "",
      name: "within 45 days Due net",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 96,
      code: "",
      name: "Baseline date on 15 of next month",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 97,
      code: "0009",
      name: "Payable in 3 partial amounts",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 98,
      code: "",
      name: "1 installment: 30.000 % with payment term 0001",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 99,
      code: "",
      name: "2 installment: 40.000 % with payment term 0001",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 100,
      code: "",
      name: "3 installment: 30.000 % with payment term 0001",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 101,
      code: "VA01",
      name: "01 Day from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 102,
      code: "VA02",
      name: "01 Day from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 103,
      code: "VA03",
      name: "02 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 104,
      code: "VA07",
      name: "03 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 105,
      code: "VA14",
      name: "07 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 106,
      code: "VA15",
      name: "14 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 107,
      code: "VA21",
      name: "15 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 108,
      code: "VA30",
      name: "21 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 109,
      code: "VA45",
      name: "30 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 110,
      code: "VA60",
      name: "45 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 111,
      code: "VA90",
      name: "60 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 112,
      code: "VI07",
      name: "90 Days from receipt of Bill",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 113,
      code: "VI15",
      name: "07 Days from date of material receipt",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 114,
      code: "VI21",
      name: "15 Days from date of material receipt",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 115,
      code: "VI30",
      name: "21 days from date of material receipt",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 116,
      code: "",
      name: "30 Days from date of material receipt",
      status: "1",
      modifiedBy: null,
    },
  ]);
}
