/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex("permission").del();
  await knex("permission").insert([
    {
      id: 2300,
      module_id: 37,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2301,
      module_id: 38,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2302,
      module_id: 40,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2303,
      module_id: 42,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2304,
      module_id: 43,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2305,
      module_id: 44,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2306,
      module_id: 45,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2307,
      module_id: 47,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2308,
      module_id: 48,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2309,
      module_id: 49,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2310,
      module_id: 51,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2311,
      module_id: 52,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2312,
      module_id: 53,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2313,
      module_id: 54,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2314,
      module_id: 55,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2315,
      module_id: 57,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2316,
      module_id: 58,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2317,
      module_id: 59,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2318,
      module_id: 60,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2319,
      module_id: 61,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2320,
      module_id: 62,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2321,
      module_id: 63,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2322,
      module_id: 64,
      role_id: 15,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2323,
      module_id: 66,
      role_id: 15,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2324,
      module_id: 37,
      role_id: 16,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2325,
      module_id: 38,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2326,
      module_id: 40,
      role_id: 16,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2327,
      module_id: 42,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2328,
      module_id: 43,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2329,
      module_id: 44,
      role_id: 16,
      createP: 0,
      readP: 1,
      updateP: 1,
      deleteP: 0,
    },
    {
      id: 2330,
      module_id: 45,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2331,
      module_id: 47,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2332,
      module_id: 48,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2333,
      module_id: 49,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2334,
      module_id: 51,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2335,
      module_id: 52,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2336,
      module_id: 53,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2337,
      module_id: 54,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2338,
      module_id: 55,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2339,
      module_id: 57,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2340,
      module_id: 58,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2341,
      module_id: 59,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2342,
      module_id: 60,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2343,
      module_id: 61,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2344,
      module_id: 62,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2345,
      module_id: 63,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2346,
      module_id: 64,
      role_id: 16,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2347,
      module_id: 66,
      role_id: 16,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2348,
      module_id: 37,
      role_id: 21,
      createP: 0,
      readP: 1,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2349,
      module_id: 38,
      role_id: 21,
      createP: 0,
      readP: 1,
      updateP: 1,
      deleteP: 0,
    },
    {
      id: 2350,
      module_id: 40,
      role_id: 21,
      createP: 0,
      readP: 1,
      updateP: 1,
      deleteP: 0,
    },
    {
      id: 2351,
      module_id: 42,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2352,
      module_id: 43,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2353,
      module_id: 44,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2354,
      module_id: 45,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2355,
      module_id: 47,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2356,
      module_id: 48,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2357,
      module_id: 49,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2358,
      module_id: 51,
      role_id: 21,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2359,
      module_id: 52,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2360,
      module_id: 53,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2361,
      module_id: 54,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2362,
      module_id: 55,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2363,
      module_id: 57,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2364,
      module_id: 58,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2365,
      module_id: 59,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2366,
      module_id: 60,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2367,
      module_id: 61,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2368,
      module_id: 62,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2369,
      module_id: 63,
      role_id: 21,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2370,
      module_id: 64,
      role_id: 21,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2371,
      module_id: 66,
      role_id: 21,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2372,
      module_id: 37,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2373,
      module_id: 38,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2374,
      module_id: 40,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2375,
      module_id: 42,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2376,
      module_id: 43,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2377,
      module_id: 44,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2378,
      module_id: 45,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2379,
      module_id: 47,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2380,
      module_id: 48,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2381,
      module_id: 49,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2382,
      module_id: 51,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2383,
      module_id: 52,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2384,
      module_id: 53,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2385,
      module_id: 54,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2386,
      module_id: 55,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2387,
      module_id: 57,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2388,
      module_id: 58,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2389,
      module_id: 59,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2390,
      module_id: 60,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2391,
      module_id: 61,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2392,
      module_id: 62,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2393,
      module_id: 63,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2394,
      module_id: 64,
      role_id: 22,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2395,
      module_id: 66,
      role_id: 22,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2396,
      module_id: 37,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2397,
      module_id: 38,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2398,
      module_id: 40,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2399,
      module_id: 42,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2400,
      module_id: 43,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2401,
      module_id: 44,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2402,
      module_id: 45,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2403,
      module_id: 47,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2404,
      module_id: 48,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2405,
      module_id: 49,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2406,
      module_id: 51,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2407,
      module_id: 52,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2408,
      module_id: 53,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2409,
      module_id: 54,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2410,
      module_id: 55,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2411,
      module_id: 57,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2412,
      module_id: 58,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2413,
      module_id: 59,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2414,
      module_id: 60,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2415,
      module_id: 61,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2416,
      module_id: 62,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2417,
      module_id: 63,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2418,
      module_id: 64,
      role_id: 23,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2419,
      module_id: 66,
      role_id: 23,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2468,
      module_id: 37,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2469,
      module_id: 38,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2470,
      module_id: 40,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2471,
      module_id: 42,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2472,
      module_id: 43,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2473,
      module_id: 44,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2474,
      module_id: 45,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2475,
      module_id: 47,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2476,
      module_id: 48,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2477,
      module_id: 49,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2478,
      module_id: 51,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2479,
      module_id: 52,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2480,
      module_id: 53,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2481,
      module_id: 54,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2482,
      module_id: 55,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2483,
      module_id: 57,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2484,
      module_id: 58,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2485,
      module_id: 59,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2486,
      module_id: 60,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2487,
      module_id: 61,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2488,
      module_id: 62,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2489,
      module_id: 63,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2490,
      module_id: 64,
      role_id: 24,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2491,
      module_id: 66,
      role_id: 24,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2492,
      module_id: 37,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2493,
      module_id: 38,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2494,
      module_id: 40,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2495,
      module_id: 42,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2496,
      module_id: 43,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2497,
      module_id: 44,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2498,
      module_id: 45,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2499,
      module_id: 47,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2500,
      module_id: 48,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2501,
      module_id: 49,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2502,
      module_id: 51,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2503,
      module_id: 52,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2504,
      module_id: 53,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2505,
      module_id: 54,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2506,
      module_id: 55,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2507,
      module_id: 57,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2508,
      module_id: 58,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2509,
      module_id: 59,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2510,
      module_id: 60,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2511,
      module_id: 61,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2512,
      module_id: 62,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2513,
      module_id: 63,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2514,
      module_id: 64,
      role_id: 25,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2515,
      module_id: 66,
      role_id: 25,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2516,
      module_id: 37,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2517,
      module_id: 38,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2518,
      module_id: 40,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2519,
      module_id: 42,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2520,
      module_id: 43,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2521,
      module_id: 44,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2522,
      module_id: 45,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2523,
      module_id: 47,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2524,
      module_id: 48,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2525,
      module_id: 49,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2526,
      module_id: 51,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2527,
      module_id: 52,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2528,
      module_id: 53,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2529,
      module_id: 54,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2530,
      module_id: 55,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2531,
      module_id: 57,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2532,
      module_id: 58,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2533,
      module_id: 59,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2534,
      module_id: 60,
      role_id: 26,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2535,
      module_id: 61,
      role_id: 26,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2536,
      module_id: 62,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2537,
      module_id: 63,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2538,
      module_id: 64,
      role_id: 26,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2539,
      module_id: 66,
      role_id: 26,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2588,
      module_id: 37,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2589,
      module_id: 38,
      role_id: 1,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2590,
      module_id: 40,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2591,
      module_id: 42,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2592,
      module_id: 43,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2593,
      module_id: 44,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2594,
      module_id: 45,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2595,
      module_id: 47,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2596,
      module_id: 48,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2597,
      module_id: 49,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2598,
      module_id: 51,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2599,
      module_id: 52,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2600,
      module_id: 53,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2601,
      module_id: 54,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2602,
      module_id: 55,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2603,
      module_id: 57,
      role_id: 1,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2604,
      module_id: 58,
      role_id: 1,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2605,
      module_id: 59,
      role_id: 1,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2606,
      module_id: 60,
      role_id: 1,
      createP: 0,
      readP: 1,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2607,
      module_id: 61,
      role_id: 1,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2608,
      module_id: 62,
      role_id: 1,
      createP: 0,
      readP: 0,
      updateP: 0,
      deleteP: 0,
    },
    {
      id: 2609,
      module_id: 63,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2610,
      module_id: 64,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
    {
      id: 2611,
      module_id: 66,
      role_id: 1,
      createP: 1,
      readP: 1,
      updateP: 1,
      deleteP: 1,
    },
  ]);
}
