/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed (knex) {
  // Deletes ALL existing entries
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex("purchase_groups").del();
  await knex("purchase_groups").insert([
    {
      id: 66,
      code: "P01",
      name: "Plant Local",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 67,
      code: "100",
      name: "Construction mat.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 68,
      code: "101",
      name: "Capex Material",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 69,
      code: "102",
      name: "Interior Material",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 70,
      code: "103",
      name: "Project Services",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 71,
      code: "104",
      name: "Planing-Civil&Arch",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 72,
      code: "105",
      name: "Admin Procurement",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 73,
      code: "106",
      name: "IT Procurement",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 74,
      code: "107",
      name: "Marketing Procure.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 75,
      code: "108",
      name: "Event Procure.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 76,
      code: "109",
      name: "Legal Dept.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 77,
      code: "110",
      name: "Business Develop.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 78,
      code: "111",
      name: "HR Consultancy ser",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 79,
      code: "112",
      name: "Proj. Cons. Design",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 80,
      code: "113",
      name: "Land",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 81,
      code: "114",
      name: "Facility Managment",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 82,
      code: "115",
      name: "Sales & distr.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 83,
      code: "116",
      name: "Fixed Asset",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 84,
      code: "117",
      name: "Planing-HVAC",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 85,
      code: "118",
      name: "Planing-PHE & FF",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 86,
      code: "119",
      name: "Planing-Elect/ELV",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 87,
      code: "120",
      name: "Interior Services",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 88,
      code: "121",
      name: "IT Services",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 89,
      code: "122",
      name: "Branding Dept.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 90,
      code: "123",
      name: "Finance Dept.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 91,
      code: "124",
      name: "Accounts Dept.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 92,
      code: "125",
      name: "MDS",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 93,
      code: "126",
      name: "Mis_ SRV_PROJ(PO16",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 94,
      code: "127",
      name: "Proj_SRV_FM-Plant",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 95,
      code: "128",
      name: "Facility_Manpwr_HO",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 96,
      code: "129",
      name: "Misc_Material_Proj",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 97,
      code: "130",
      name: "SITC-Order_Project",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 98,
      code: "131",
      name: "Mis_SRV_HOSP(PO16)",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 99,
      code: "132",
      name: "Mis_SRV_Renv(PO16)",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 100,
      code: "133",
      name: "Consult_HOSP(PO08)",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 101,
      code: "134",
      name: "Consult_Renv(PO08)",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 102,
      code: "200",
      name: "ARDL-CC Raipur-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 103,
      code: "201",
      name: "ARDL-Ecocentre",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 104,
      code: "202",
      name: "ARDL-CC-RP LEASE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 105,
      code: "203",
      name: "ARDL-CC-Silig–FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 106,
      code: "204",
      name: "ARDL-CC-Silig–MPX",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 107,
      code: "205",
      name: "ARDL–CC–RP-MPLX",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 108,
      code: "206",
      name: "ARDL–CC–RP-Event",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 109,
      code: "207",
      name: "ARDL–CCSG-Event",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 110,
      code: "208",
      name: "ARDL-CCHD-LEASE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 111,
      code: "209",
      name: "ARDL-CCHD-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 112,
      code: "210",
      name: "ARDL-CCHD-EVENTS",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 113,
      code: "211",
      name: "ARDL-CC-HALDIA",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 114,
      code: "212",
      name: "ARDL–CCHD–MULTIPLE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 115,
      code: "213",
      name: "ARDL–CCSLG-EXT",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 116,
      code: "214",
      name: "ARDL– UTTAM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 117,
      code: "215",
      name: "ARDL–ECOSPACE-LEAS",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 118,
      code: "216",
      name: "ARDL–ECOSPACE-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 119,
      code: "217",
      name: "ARDL–ECOSPACE-EVEN",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 120,
      code: "218",
      name: "ARDL–CC–RP-CON",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 121,
      code: "219",
      name: "ARDL-FSM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 122,
      code: "220",
      name: "ARDL–ECOCENTRE-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 123,
      code: "221",
      name: "ARDL-ECOCNTR-LEASE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 124,
      code: "225",
      name: "USL-CC-Patna",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 125,
      code: "226",
      name: "USL - CCPT-LEASE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 126,
      code: "227",
      name: "USL-CCPT-EVENTS",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 127,
      code: "228",
      name: "USL - CCPT-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 128,
      code: "229",
      name: "USL-RESIDENCY-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 129,
      code: "235",
      name: "MIPL-Ecospace-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 130,
      code: "236",
      name: "MIPL-Ecospace-Leas",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 131,
      code: "237",
      name: "MIPL_ECOSPACE_EVEN",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 132,
      code: "240",
      name: "UGDL-Ecospace-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 133,
      code: "241",
      name: "UGDL-Ecospace-Leas",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 134,
      code: "242",
      name: "UGDL_ECOSPACE_EVEN",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 135,
      code: "243",
      name: "SRPL-RAIPUR RESID",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 136,
      code: "250",
      name: "SEBRL-Uttalika",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 137,
      code: "251",
      name: "SEBRL-UTALIKA -FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 138,
      code: "252",
      name: "SEBRL-UTLIKA-HIG-F",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 139,
      code: "253",
      name: "SEBRL-UTLIKA CLB-F",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 140,
      code: "255",
      name: "AREML-CC-Saltlake",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 141,
      code: "256",
      name: "AREML-CC-Newtown",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 142,
      code: "257",
      name: "AREML-CC-Raipur",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 143,
      code: "260",
      name: "QMVL-CC-Saltlake",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 144,
      code: "261",
      name: "QMVL-CC-Newtown",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 145,
      code: "262",
      name: "QMVL - HIDCO CC",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 146,
      code: "263",
      name: "QMVL-ML ACROPOLIS-",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 147,
      code: "264",
      name: "QMVL-NBCC SQUARE F",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 148,
      code: "265",
      name: "VPPL - CHIA KUTIR",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 149,
      code: "266",
      name: "VPPL-CHIA KUTIR-VI",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 150,
      code: "267",
      name: "QMVL-DHONO DHANYO",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 151,
      code: "268",
      name: "QMVL-HIMALAYAN BUI",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 152,
      code: "270",
      name: "ANHVL-ECO RESORT",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 153,
      code: "271",
      name: "ANHVL-DIGHA",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 154,
      code: "272",
      name: "ANLVL - CCSL-LEASE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 155,
      code: "273",
      name: "ANHVL-SURABHI EXTN",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 156,
      code: "274",
      name: "ANHVL-STUDIO MALLI",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 157,
      code: "277",
      name: "BAHDL–ECOSPACE RES",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 158,
      code: "278",
      name: "ANHVL-KALICHARANPU",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 159,
      code: "279",
      name: "ANHVL-GANGAAWAS RE",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 160,
      code: "280",
      name: "BAHDL-UTSAAV",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 161,
      code: "281",
      name: "BAHDL - CCNT ANNEX",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 162,
      code: "282",
      name: "BAHDL-UPOHAR-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 163,
      code: "283",
      name: "BAHDL-UPOHAR-PROJ",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 164,
      code: "284",
      name: "BAHDL - CCNT",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 165,
      code: "285",
      name: "BAHDL - GHUNI RES",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 166,
      code: "286",
      name: "BAHDL-UJJWALA-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 167,
      code: "287",
      name: "GGL - BL PROJECT",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 168,
      code: "288",
      name: "BAHDL-UTTSAV PK-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 169,
      code: "300",
      name: "AHUICL-ECOSTATION",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 170,
      code: "301",
      name: "AHUICL–ECOSUITE-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 171,
      code: "302",
      name: "AHUICL-KALIKAPUR",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 172,
      code: "303",
      name: "AHUICL–UDVITA",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 173,
      code: "304",
      name: "AHUICL - UJAAS- FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 174,
      code: "305",
      name: "AHUICL-AAMTALA TOW",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 175,
      code: "306",
      name: "AHUICL-UDVITA-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 176,
      code: "307",
      name: "AHUICL - SERVICES",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 177,
      code: "315",
      name: "BHL - HOTEL",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 178,
      code: "325",
      name: "CPHRL - PANTHANG",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 179,
      code: "326",
      name: "CPHRL - RABONGLA",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 180,
      code: "336",
      name: "GEHRCL - LATAGURI",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 181,
      code: "346",
      name: "SRAPL- HIMAL KUTIR",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 182,
      code: "356",
      name: "CEL-FSM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 183,
      code: "365",
      name: "ANTDPL-UTSODHAAR",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 184,
      code: "366",
      name: "ANTDPL-MONTANA GYM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 185,
      code: "367",
      name: "ANTDPL-UTSODARA-EW",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 186,
      code: "368",
      name: "ANTDPL-UTSDARA-H02",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 187,
      code: "369",
      name: "UTSODHAARA PLOT-FM",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 188,
      code: "400",
      name: "HOSP_Project_ mat.",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 189,
      code: "401",
      name: "HOSP Capex(Srv/Mat",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 190,
      code: "402",
      name: "HOSP Services",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 191,
      code: "451",
      name: "Ren-HOSP_Proj_Mat",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 192,
      code: "452",
      name: "Ren-HOSP-Capex_S&M",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 193,
      code: "453",
      name: "Ren-HOSP- Services",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 194,
      code: "900",
      name: "Land Project-1",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 195,
      code: "901",
      name: "Land Project-2",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 196,
      code: "902",
      name: "Land Project-3",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 197,
      code: "903",
      name: "Land Project-4",
      status: "1",
      modifiedBy: null,
    },
    {
      id: 198,
      code: "904",
      name: "Land Project-5",
      status: "1",
      modifiedBy: null,
    },
  ]);
}
